# Machine-readable feature matrix: which languages support which editor/notebook features.
#
# Everything here is derived from the actual module evaluation (`everythingEnv`), so it
# can't drift from the code the way a hand-written table would. The one exception is the
# language-server capability data, which can't be known without running the servers; that
# lives in ./lsp-capabilities.json and is regenerated by scripts/probe-lsp-capabilities.
#
# Consumers: `nix build .#featureMatrixJson` (raw data),
#            `nix build .#featureMatrixMarkdown` / `.#featureMatrixSvg` (rendered).

{ lib
, everythingEnv
, kernels
, lspCapabilitiesFile ? ./lsp-capabilities.json
}:

let
  kernelOptions = everythingEnv.options.kernels;

  lspCapabilities =
    if builtins.pathExists lspCapabilitiesFile
    then (builtins.fromJSON (builtins.readFile lspCapabilitiesFile)).kernels or {}
    else {};

  # ---------------------------------------------------------------------------
  # Column definitions
  # ---------------------------------------------------------------------------

  groups = [
    { id = "core"; name = "Notebook"; }
    { id = "intelligence"; name = "Code intelligence"; }
    { id = "navigation"; name = "Navigation"; }
    { id = "editing"; name = "Editing"; }
    { id = "packages"; name = "Packages"; }
  ];

  # source = "nix": computed from the module evaluation below.
  # source = "lsp": read out of the language server's advertised capabilities.
  features = [
    { id = "jupyterKernel"; name = "Jupyter kernel"; group = "core";
      description = "Runs notebook cells through a Jupyter kernel."; source = "nix"; }
    { id = "repl"; name = "REPL"; group = "core";
      description = "Ships an interactive console you can attach to the same session."; source = "nix"; }
    { id = "variableInspector"; name = "Variable inspector"; group = "core";
      description = "Lists the variables currently defined in the session, with drill-down."; source = "nix"; }
    { id = "debugger"; name = "Debugger"; group = "core";
      description = "Breakpoints and stepping via the Jupyter debug protocol."; source = "nix"; }
    { id = "syntaxHighlighting"; name = "Syntax highlighting"; group = "core";
      description = "Editor highlighting for the language."; source = "nix"; }

    { id = "languageServer"; name = "Language server"; group = "intelligence";
      description = "An LSP server is wired up for notebook cells and files."; source = "nix"; }
    { id = "completion"; name = "Code completion"; group = "intelligence";
      description = "Context-aware completions as you type."; source = "lsp"; }
    { id = "hover"; name = "Hover docs"; group = "intelligence";
      description = "Type and documentation popups on hover."; source = "lsp"; }
    { id = "signatureHelp"; name = "Signature help"; group = "intelligence";
      description = "Parameter hints while calling a function."; source = "lsp"; }
    { id = "diagnostics"; name = "Diagnostics"; group = "intelligence";
      description = "Errors, warnings and lints reported inline."; source = "lsp"; }
    { id = "semanticTokens"; name = "Semantic highlighting"; group = "intelligence";
      description = "Highlighting driven by the compiler/analyzer rather than a regex grammar."; source = "lsp"; }
    { id = "inlayHints"; name = "Inlay hints"; group = "intelligence";
      description = "Inferred types and parameter names rendered inline."; source = "lsp"; }

    { id = "definition"; name = "Jump to definition"; group = "navigation";
      description = "Go from a use of a symbol to where it's defined."; source = "lsp"; }
    { id = "typeDefinition"; name = "Jump to type definition"; group = "navigation";
      description = "Go from a value to the definition of its type."; source = "lsp"; }
    { id = "references"; name = "Find references"; group = "navigation";
      description = "Find every use of a symbol."; source = "lsp"; }
    { id = "documentSymbols"; name = "Document outline"; group = "navigation";
      description = "Symbol tree for the current document."; source = "lsp"; }
    { id = "workspaceSymbols"; name = "Workspace symbol search"; group = "navigation";
      description = "Search symbols across the whole project."; source = "lsp"; }
    { id = "documentHighlight"; name = "Highlight occurrences"; group = "navigation";
      description = "Highlights other occurrences of the symbol under the cursor."; source = "lsp"; }

    { id = "formatting"; name = "Formatting"; group = "editing";
      description = "Format a document or a selection."; source = "lsp"; }
    { id = "rename"; name = "Rename symbol"; group = "editing";
      description = "Rename a symbol and every reference to it."; source = "lsp"; }
    { id = "codeActions"; name = "Code actions"; group = "editing";
      description = "Quick fixes and refactorings offered on a range."; source = "lsp"; }

    { id = "subPackageManagement"; name = "Subpackage management"; group = "packages";
      description = "A searchable set of language packages you can add to the environment "
                    + "declaratively."; source = "nix"; }
  ];

  # ---------------------------------------------------------------------------
  # LSP capability lookup
  # ---------------------------------------------------------------------------

  # Feature id -> the field of the LSP `initialize` result that backs it. `null` means
  # the feature isn't advertised in capabilities and needs special handling below.
  lspCapabilityField = {
    completion = "completionProvider";
    hover = "hoverProvider";
    signatureHelp = "signatureHelpProvider";
    semanticTokens = "semanticTokensProvider";
    inlayHints = "inlayHintProvider";
    definition = "definitionProvider";
    typeDefinition = "typeDefinitionProvider";
    references = "referencesProvider";
    documentSymbols = "documentSymbolProvider";
    workspaceSymbols = "workspaceSymbolProvider";
    documentHighlight = "documentHighlightProvider";
    formatting = "documentFormattingProvider";
    rename = "renameProvider";
    codeActions = "codeActionProvider";
    diagnostics = null;
  };

  # A capability is "advertised" if the server returned anything other than false/null for it.
  advertises = caps: field:
    let v = caps.${field} or false;
    in if builtins.isBool v then v else (v != null);

  # Merge over every language server enabled for a kernel: a feature counts as supported if
  # any of them provides it.
  lspSupport = kernelName: featureId:
    let
      probed = lspCapabilities ? ${kernelName};
      servers = lspCapabilities.${kernelName} or {};
      serverNames = builtins.attrNames servers;
      field = lspCapabilityField.${featureId} or null;

      providedBy =
        if field == null then []
        else builtins.filter (n: advertises (servers.${n}.capabilities or {}) field) serverNames;
    in
      # No probe data for this kernel at all is different from "probed, has no servers".
      if !probed then { level = "unknown"; detail = null; }
      else if serverNames == [] then { level = "none"; detail = null; }
      else if featureId == "diagnostics" then
        # Diagnostics are pushed with textDocument/publishDiagnostics, which servers don't
        # advertise. Treat pull diagnostics as the strong signal and a live server as the weak one.
        let pullers = builtins.filter (n: advertises (servers.${n}.capabilities or {}) "diagnosticProvider") serverNames;
        in if pullers != []
           then { level = "full"; detail = "pull + push"; }
           else { level = "full"; detail = "push"; }
      else if providedBy == [] then { level = "none"; detail = null; }
      else { level = "full"; detail = lib.concatStringsSep ", " providedBy; };

  # ---------------------------------------------------------------------------
  # Per-kernel facts from the module evaluation
  # ---------------------------------------------------------------------------

  kernelInfo = name: kernel:
    let
      opts = kernelOptions.${name} or {};
      meta = kernel.meta or {};
      version = meta.version or null;

      # meta.displayName sometimes carries the version ("Bash 5.3p9"); strip it for a clean label.
      rawDisplayName = meta.displayName or meta.name or name;
      displayName =
        if version != null && lib.hasSuffix " ${version}" rawDisplayName
        then lib.removeSuffix " ${version}" rawDisplayName
        else rawDisplayName;

      availableLanguageServers = builtins.attrNames (opts.lsp or {});
      enabledLanguageServers = kernel.languageServerNames or [];

      repls = builtins.attrNames (kernel.repls or {});
      hasVariableInspector = (opts.misc or {}) ? enableVariableInspector;
      hasPackages = meta.hasPackages or false;

      nixSupport = {
        jupyterKernel = { level = "full"; detail = null; };
        repl = if repls == []
               then { level = "none"; detail = null; }
               else { level = "full"; detail = lib.concatStringsSep ", " repls; };
        variableInspector = { level = if hasVariableInspector then "full" else "none"; detail = null; };
        debugger = { level = if meta.hasDebugger or false then "full" else "none"; detail = null; };
        syntaxHighlighting =
          let mode = (kernel.modes or {}).code_mirror_mode or null;
          in { level = if mode == null then "none" else "full"; detail = mode; };
        languageServer = if enabledLanguageServers == []
                         then { level = "none"; detail = null; }
                         else { level = "full"; detail = lib.concatStringsSep ", " enabledLanguageServers; };
        subPackageManagement = { level = if hasPackages then "full" else "none"; detail = null; };
      };

      supportFor = feature:
        if feature.source == "lsp"
        then lspSupport name feature.id
        else nixSupport.${feature.id} or { level = "unknown"; detail = null; };
    in
      {
        id = name;
        inherit displayName version;
        description = meta.description or null;
        attrs = (kernel.modes or {}).attrs or [];
        extensions = (kernel.modes or {}).extensions or [];
        # Repo-relative rather than a store path, so the JSON is stable across rebuilds
        # and a consumer can find the file in a checkout.
        iconMonochrome =
          if meta ? iconMonochrome
          then lib.removePrefix "${toString ../.}/" (toString meta.iconMonochrome)
          else null;
        componentVersions = kernel.versions or {};
        languageServers = {
          available = availableLanguageServers;
          enabledByDefault = enabledLanguageServers;
          probed = builtins.attrNames (lspCapabilities.${name} or {});
        };
        support = lib.listToAttrs (map (f: lib.nameValuePair f.id (supportFor f)) features);
      };

  # Sort rows by display name so the table is stable and readable.
  languages = lib.sort (a: b: a.displayName < b.displayName)
    (lib.mapAttrsToList kernelInfo kernels);

in

{
  schemaVersion = 1;
  inherit groups features languages;

  # Which parts of the data came from a live probe vs. pure evaluation.
  provenance = {
    nix = "Evaluated from the codedown-languages module system (nix/feature-matrix.nix).";
    lsp = "Read from language server `initialize` responses (nix/lsp-capabilities.json, "
          + "regenerated by scripts/probe-lsp-capabilities).";
    lspProbedKernels = builtins.attrNames lspCapabilities;
  };
}
