# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "dba48d99a7ad89f5ec4a8e2d87303de1987ac6e1";
  registrySha256 = "1k56xzilsy0pc20hr1yhrsa3dwbhm0vdyfbgz5mianqc704mw3cd";
  rootPackages = ["LanguageServer" "SymbolServer"];
  closure = [{
  name = "ArgTools";
  uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f";
  path = "A/ArgTools";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "CSTParser";
  uuid = "00ebfdb7-1f24-5e51-bd34-a7502290713f";
  path = "C/CSTParser";
  replaceUrlInManifest = null;
  treehash = "3ddd48d200eb8ddf9cb3e0189fc059fd49b97c1f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/julia-vscode/CSTParser.jl.git"; rev = "3ddd48d200eb8ddf9cb3e0189fc059fd49b97c1f"; sha256 = "1w3yav6z2qv4l3hixf57alin18c4jqpp9rll852kd13lpzymj37k"; };
} {
  name = "CommonMark";
  uuid = "a80b9123-70ca-4bc0-993e-6e3bcb318db6";
  path = "C/CommonMark";
  replaceUrlInManifest = null;
  treehash = "86cce6fd164c26bad346cc51ca736e692c9f553c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/MichaelHatherly/CommonMark.jl.git"; rev = "86cce6fd164c26bad346cc51ca736e692c9f553c"; sha256 = "0a7xmlzn2ll9wil70m031i7kvrf1nv6rlpr82fggpldl8qjdfwf3"; };
} {
  name = "Compat";
  uuid = "34da2185-b29b-5c13-b0c7-acf172513d20";
  path = "C/Compat";
  replaceUrlInManifest = null;
  treehash = "00a2cccc7f098ff3b66806862d275ca3db9e6e5a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Compat.jl.git"; rev = "00a2cccc7f098ff3b66806862d275ca3db9e6e5a"; sha256 = "1b0mm6lbcm16z3hdbm4m73p7lqdgznzk8ycpzjp32v0ljm7zqh7n"; };
} {
  name = "Crayons";
  uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f";
  path = "C/Crayons";
  replaceUrlInManifest = null;
  treehash = "249fe38abf76d48563e2f4556bebd215aa317e15";
  artifacts = {};
  src = fetchgit { url = "https://github.com/KristofferC/Crayons.jl.git"; rev = "249fe38abf76d48563e2f4556bebd215aa317e15"; sha256 = "0vfbb02pclwlbpcl7rhr98a495kga5wydf5wz1gp1xn1wxgpgxpd"; };
} {
  name = "DataStructures";
  uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8";
  path = "D/DataStructures";
  replaceUrlInManifest = null;
  treehash = "d1fff3a548102f48987a52a2e0d114fa97d730f0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/DataStructures.jl.git"; rev = "d1fff3a548102f48987a52a2e0d114fa97d730f0"; sha256 = "1ikrgc4d39980nrr77yzcnr1v74wrjh9xvyi2ajfzbcim58vrcqg"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Downloads";
  uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6";
  path = "D/Downloads";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Glob";
  uuid = "c27321d9-0574-5035-807b-f59d2c89b15c";
  path = "G/Glob";
  replaceUrlInManifest = null;
  treehash = "4df9f7e06108728ebf00a0a11edee4b29a482bb2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/vtjnash/Glob.jl.git"; rev = "4df9f7e06108728ebf00a0a11edee4b29a482bb2"; sha256 = "164a404b61y5p7shrq3mvz1bi45j6v6pgqyi4shqpbx6rmnh6hp0"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "JSON";
  uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6";
  path = "J/JSON";
  replaceUrlInManifest = null;
  treehash = "3c837543ddb02250ef42f4738347454f95079d4e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/JSON.jl.git"; rev = "3c837543ddb02250ef42f4738347454f95079d4e"; sha256 = "1l2p852sxq6h5fif3dqshvbw17gb06jmq2nkr88spvp7s0n0nslz"; };
} {
  name = "JSONRPC";
  uuid = "b9b8584e-8fd3-41f9-ad0c-7255d428e418";
  path = "J/JSONRPC";
  replaceUrlInManifest = null;
  treehash = "28f19147ccfcb02e29bd96a14110e032d00be30a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/julia-vscode/JSONRPC.jl.git"; rev = "28f19147ccfcb02e29bd96a14110e032d00be30a"; sha256 = "1hmjbx8n6rgcrhkwznvvx5s2mlzbd1sq6krwlbcz8m4jkr5jkj9y"; };
} {
  name = "JuliaFormatter";
  uuid = "98e50ef6-434e-11e9-1051-2b60c6c9e899";
  path = "J/JuliaFormatter";
  replaceUrlInManifest = null;
  treehash = "76ee67858b65133b2460b0eebf52e49950bb90a3";
  artifacts = {};
  src = fetchgit { url = "https://github.com/domluna/JuliaFormatter.jl.git"; rev = "76ee67858b65133b2460b0eebf52e49950bb90a3"; sha256 = "1llgsh00c09yd6f4cklzisspxjx25x16mp44l8x4xjrlr8gbddxk"; };
} {
  name = "LanguageServer";
  uuid = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7";
  path = "L/LanguageServer";
  replaceUrlInManifest = null;
  treehash = "90fab8ca9a9515d099ee7a7df5afc2e11ffdbb37";
  artifacts = {};
  src = fetchgit { url = "https://github.com/julia-vscode/LanguageServer.jl.git"; rev = "90fab8ca9a9515d099ee7a7df5afc2e11ffdbb37"; sha256 = "08f0lvw0fj4z45pm3wj11viv6glq0hccrliw1jcacj3rqk5p5jsl"; };
} {
  name = "LibCURL";
  uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21";
  path = "L/LibCURL";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibCURL_jll";
  uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0";
  path = "L/LibCURL_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibSSH2_jll";
  uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8";
  path = "L/LibSSH2_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MozillaCACerts_jll";
  uuid = "14a3606d-f60d-562e-9121-12d972cd8159";
  path = "M/MozillaCACerts_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "NetworkOptions";
  uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908";
  path = "N/NetworkOptions";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "OrderedCollections";
  uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d";
  path = "O/OrderedCollections";
  replaceUrlInManifest = null;
  treehash = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"; rev = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"; sha256 = "0jaxcmvkp8zpqrz101yikdigz90s70i7in5wn8kybwzf0na3lhwf"; };
} {
  name = "Parsers";
  uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0";
  path = "P/Parsers";
  replaceUrlInManifest = null;
  treehash = "b64719e8b4504983c7fca6cc9db3ebc8acc2a4d6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Parsers.jl.git"; rev = "b64719e8b4504983c7fca6cc9db3ebc8acc2a4d6"; sha256 = "1zzg594q862qvpaww8689hvianbi8li944jyqfbwmjinhl7nj7qd"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SnoopPrecompile";
  uuid = "66db9d55-30c0-4569-8b51-7e840670fc0c";
  path = "S/SnoopPrecompile";
  replaceUrlInManifest = null;
  treehash = "f604441450a3c0569830946e5b33b78c928e1a85";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/SnoopCompile.jl.git"; rev = "f604441450a3c0569830946e5b33b78c928e1a85"; sha256 = "01krnwnrnf6i70zi1h4cwchrv20kzr4lr05hc2j2m3r3waf4vz9h"; };
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "StaticLint";
  uuid = "b3cc710f-9c33-5bdb-a03d-a94903873e97";
  path = "S/StaticLint";
  replaceUrlInManifest = null;
  treehash = "1152934b19a8a296db95ef6e1d454d4acc2aa79d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/julia-vscode/StaticLint.jl.git"; rev = "1152934b19a8a296db95ef6e1d454d4acc2aa79d"; sha256 = "06dsliw2chrbb9zq3g6snw58gr812mzgdww6c16mlrwgvbr58ssj"; };
} {
  name = "SymbolServer";
  uuid = "cf896787-08d5-524d-9de7-132aaa0cb996";
  path = "S/SymbolServer";
  replaceUrlInManifest = null;
  treehash = "d675e3a860523660421b1ca33543c06db2783a9b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/julia-vscode/SymbolServer.jl.git"; rev = "d675e3a860523660421b1ca33543c06db2783a9b"; sha256 = "0di754fzc42bj3c0clcql2s2a0xxf78k4l83zjk9amgh100xbs49"; };
} {
  name = "TOML";
  uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76";
  path = "T/TOML";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Tar";
  uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e";
  path = "T/Tar";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Tokenize";
  uuid = "0796e94c-ce3b-5d07-9a54-7f471281c624";
  path = "T/Tokenize";
  replaceUrlInManifest = null;
  treehash = "2b3af135d85d7e70b863540160208fa612e736b9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Tokenize.jl.git"; rev = "2b3af135d85d7e70b863540160208fa612e736b9"; sha256 = "1l3dy6nad0viavzy26lfnhzpd3gcxgaq7yvm7h1ja280xsh60p3i"; };
} {
  name = "URIs";
  uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4";
  path = "U/URIs";
  replaceUrlInManifest = null;
  treehash = "ac00576f90d8a259f2c9d823e91d1de3fd44d348";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/URIs.jl.git"; rev = "ac00576f90d8a259f2c9d823e91d1de3fd44d348"; sha256 = "1sd0f5zbp5inn845xbm2k97dcb4yixr3yp9f14dngd44by18p93v"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Zlib_jll";
  uuid = "83775a58-1f1d-513f-b197-d71354ab007a";
  path = "Z/Zlib_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "nghttp2_jll";
  uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d";
  path = "N/nghttp2_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "p7zip_jll";
  uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0";
  path = "P/p7zip_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
}];
}
