# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "2617006e20e3f62a777490522e66bfc3370b953c";
  registrySha256 = "0r8y13drdkyksh1d7r44qddvpmhaajw8ns14q2klvgps2a7dr0nl";
  rootPackages = ["IJulia" "Plots"];
  closure = [{
  name = "ArgTools";
  uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f";
  path = "A/ArgTools";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "BitFlags";
  uuid = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35";
  path = "B/BitFlags";
  replaceUrlInManifest = null;
  treehash = "43b1a4a8f797c1cddadf60499a8a077d4af2cd2d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/jmert/BitFlags.jl.git"; rev = "43b1a4a8f797c1cddadf60499a8a077d4af2cd2d"; sha256 = "1wphfpwqm7bsff68d6h9yhhxrh1lq2shyl0afbzp0h5czf6qi2xr"; };
} {
  name = "Bzip2_jll";
  uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0";
  path = "B/Bzip2_jll";
  replaceUrlInManifest = null;
  treehash = "19a35467a82e236ff51bc17a3a44b69ef35185a2";
  artifacts = {
    "7661e5a9aa217ce3c468389d834a4fb43b0911e8" = [{
      name = "Bzip2";
      url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.x86_64-linux-gnu.tar.gz";
      sha256 = "7cac890c49ed760223194100c84c701ecba65fcc2b0a8916950c19143c3bbddb";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl.git"; rev = "19a35467a82e236ff51bc17a3a44b69ef35185a2"; sha256 = "0ajhj3l81p7yrzsga3xmsdz8igsjnyx6daya7z552szia5g563bj"; };
} {
  name = "Cairo_jll";
  uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a";
  path = "C/Cairo_jll";
  replaceUrlInManifest = null;
  treehash = "4b859a208b2397a7a623a03449e4636bdb17bcf2";
  artifacts = {
    "8b0284dc2781b9481ff92e281f1db532d8421040" = [{
      name = "Cairo";
      url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.1+0/Cairo.v1.16.1.x86_64-linux-gnu.tar.gz";
      sha256 = "34627fe21b932eb8afc1607c96ebe032f9e7dcc77c33fc679563c29d3d4b53aa";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl.git"; rev = "4b859a208b2397a7a623a03449e4636bdb17bcf2"; sha256 = "18q4wbg6hdi6wndmgvkfilhay2b0sinzfbyd1vb414g107ikg1l4"; };
} {
  name = "ChainRulesCore";
  uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4";
  path = "C/ChainRulesCore";
  replaceUrlInManifest = null;
  treehash = "e7ff6cadf743c098e08fca25c91103ee4303c9bb";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/ChainRulesCore.jl.git"; rev = "e7ff6cadf743c098e08fca25c91103ee4303c9bb"; sha256 = "0v1hyala8crjwkii9w86gsixpdxp5y6wg24w6qcsbjqnx0gnsiy3"; };
} {
  name = "ChangesOfVariables";
  uuid = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0";
  path = "C/ChangesOfVariables";
  replaceUrlInManifest = null;
  treehash = "38f7a08f19d8810338d4f5085211c7dfa5d5bdd8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/ChangesOfVariables.jl.git"; rev = "38f7a08f19d8810338d4f5085211c7dfa5d5bdd8"; sha256 = "1migyhiqr1rq496302wlkb0s5l8zwqs97ajfkip0jzpvrk2s2xxy"; };
} {
  name = "CodecZlib";
  uuid = "944b1d66-785c-5afd-91f1-9de20f533193";
  path = "C/CodecZlib";
  replaceUrlInManifest = null;
  treehash = "ded953804d019afa9a3f98981d99b33e3db7b6da";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/CodecZlib.jl.git"; rev = "ded953804d019afa9a3f98981d99b33e3db7b6da"; sha256 = "0xm603nylkwk4bzx66zv1g3syzrvn3jh9spdx7kvcvgszzyrrgh4"; };
} {
  name = "ColorSchemes";
  uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4";
  path = "C/ColorSchemes";
  replaceUrlInManifest = null;
  treehash = "aa3edc8f8dea6cbfa176ee12f7c2fc82f0608ed3";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/ColorSchemes.jl.git"; rev = "aa3edc8f8dea6cbfa176ee12f7c2fc82f0608ed3"; sha256 = "0aiyvwllsrjsn98n3sxl63zjdc64g279f8hpcg5zpa2v6172ayfd"; };
} {
  name = "ColorTypes";
  uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f";
  path = "C/ColorTypes";
  replaceUrlInManifest = null;
  treehash = "eb7f0f8307f71fac7c606984ea5fb2817275d6e4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/ColorTypes.jl.git"; rev = "eb7f0f8307f71fac7c606984ea5fb2817275d6e4"; sha256 = "134n88gmyl2ylpi5dzly25wg6z63xci89d9rzvzxcw5qxwrn4dc1"; };
} {
  name = "ColorVectorSpace";
  uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4";
  path = "C/ColorVectorSpace";
  replaceUrlInManifest = null;
  treehash = "d08c20eef1f2cbc6e60fd3612ac4340b89fea322";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/ColorVectorSpace.jl.git"; rev = "d08c20eef1f2cbc6e60fd3612ac4340b89fea322"; sha256 = "07scws2bn2z3f2crhnx1zxk3zk3vzfv9iz6lv3i9785nplmsgdx9"; };
} {
  name = "Colors";
  uuid = "5ae59095-9a9b-59fe-a467-6f913c188581";
  path = "C/Colors";
  replaceUrlInManifest = null;
  treehash = "417b0ed7b8b838aa6ca0a87aadf1bb9eb111ce40";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/Colors.jl.git"; rev = "417b0ed7b8b838aa6ca0a87aadf1bb9eb111ce40"; sha256 = "0kx3hq7rf8p5zx6ly9k5j90zijmc7yrwmy96cgkl2ibdfbnhmya3"; };
} {
  name = "Compat";
  uuid = "34da2185-b29b-5c13-b0c7-acf172513d20";
  path = "C/Compat";
  replaceUrlInManifest = null;
  treehash = "aaabba4ce1b7f8a9b34c015053d3b1edf60fa49c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Compat.jl.git"; rev = "aaabba4ce1b7f8a9b34c015053d3b1edf60fa49c"; sha256 = "1a7qz6vbin9zsfvnkcdrah0nc37ggic3p42pqh71pfnknkn8by1b"; };
} {
  name = "CompilerSupportLibraries_jll";
  uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae";
  path = "C/CompilerSupportLibraries_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Conda";
  uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d";
  path = "C/Conda";
  replaceUrlInManifest = null;
  treehash = "6e47d11ea2776bc5627421d59cdcc1296c058071";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPy/Conda.jl.git"; rev = "6e47d11ea2776bc5627421d59cdcc1296c058071"; sha256 = "0m7yv7yqcdyd4z7c5qxm6c9dhfwmmdaxg04i2jxhmdk2r6l63mrn"; };
} {
  name = "Contour";
  uuid = "d38c429a-6771-53c6-b99e-75d170b6e991";
  path = "C/Contour";
  replaceUrlInManifest = null;
  treehash = "d05d9e7b7aedff4e5b51a029dced05cfb6125781";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGeometry/Contour.jl.git"; rev = "d05d9e7b7aedff4e5b51a029dced05cfb6125781"; sha256 = "14pxmimq6f7s9lrg2y4xr5far1gafvihrp80q4qrncwv74ahr7nq"; };
} {
  name = "DataAPI";
  uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a";
  path = "D/DataAPI";
  replaceUrlInManifest = null;
  treehash = "e08915633fcb3ea83bf9d6126292e5bc5c739922";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/DataAPI.jl.git"; rev = "e08915633fcb3ea83bf9d6126292e5bc5c739922"; sha256 = "1x5pdpjlbk29766ark7rmzjbl0rhxmsb1cp04lc891aknh30rn3i"; };
} {
  name = "DataStructures";
  uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8";
  path = "D/DataStructures";
  replaceUrlInManifest = null;
  treehash = "d1fff3a548102f48987a52a2e0d114fa97d730f0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/DataStructures.jl.git"; rev = "d1fff3a548102f48987a52a2e0d114fa97d730f0"; sha256 = "1ikrgc4d39980nrr77yzcnr1v74wrjh9xvyi2ajfzbcim58vrcqg"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DelimitedFiles";
  uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab";
  path = "D/DelimitedFiles";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DocStringExtensions";
  uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae";
  path = "D/DocStringExtensions";
  replaceUrlInManifest = null;
  treehash = "c36550cb29cbe373e95b3f40486b9a4148f89ffd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDocs/DocStringExtensions.jl.git"; rev = "c36550cb29cbe373e95b3f40486b9a4148f89ffd"; sha256 = "0qmwij9wf5f8hmzx7ar2lymcb2aadlryam4h8221gy30d4z8ycwn"; };
} {
  name = "Downloads";
  uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6";
  path = "D/Downloads";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Expat_jll";
  uuid = "2e619515-83b5-522b-bb60-26c02a35a201";
  path = "E/Expat_jll";
  replaceUrlInManifest = null;
  treehash = "bad72f730e9e91c08d9427d5e8db95478a3c323d";
  artifacts = {
    "fac7e6d8fc4c5775bf5118ab494120d2a0db4d64" = [{
      name = "Expat";
      url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.4.8+0/Expat.v2.4.8.x86_64-linux-gnu.tar.gz";
      sha256 = "8acd5348597acf68c3dd8ac07b51a6069828507cfd2e438ee964a2ca777b64ff";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl.git"; rev = "bad72f730e9e91c08d9427d5e8db95478a3c323d"; sha256 = "0707k4nplmlc2yr229jqv04xhi172pinlplh4qmrbiyqzs8198zg"; };
} {
  name = "FFMPEG";
  uuid = "c87230d0-a227-11e9-1b43-d7ebe4e7570a";
  path = "F/FFMPEG";
  replaceUrlInManifest = null;
  treehash = "b57e3acbe22f8484b4b5ff66a7499717fe1a9cc8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/FFMPEG.jl.git"; rev = "b57e3acbe22f8484b4b5ff66a7499717fe1a9cc8"; sha256 = "1ldxbp0kq3ip67x7sp82dz56aq4p5i0chspbgx2zgskr6jcbjj1b"; };
} {
  name = "FFMPEG_jll";
  uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5";
  path = "F/FFMPEG_jll";
  replaceUrlInManifest = null;
  treehash = "74faea50c1d007c85837327f6775bea60b5492dd";
  artifacts = {
    "b409c0eafb4254a980f9e730f6fbe56867890f6a" = [{
      name = "FFMPEG";
      url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.4.2+2/FFMPEG.v4.4.2.x86_64-linux-gnu.tar.gz";
      sha256 = "a8a79f5237d093a8d07cb2a40cbd15c2cfb1310c6c3ae358eb825bb1ec92e0e2";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl.git"; rev = "74faea50c1d007c85837327f6775bea60b5492dd"; sha256 = "09nk28in2vssb299l61qh28s0gz1nzfakgj8nm58mkgvil15s56i"; };
} {
  name = "FileWatching";
  uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "FixedPointNumbers";
  uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93";
  path = "F/FixedPointNumbers";
  replaceUrlInManifest = null;
  treehash = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/FixedPointNumbers.jl.git"; rev = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"; sha256 = "0j0n40n04q9sk68wh9jq90m6c67k4ws02k41djjzkrqmpzv4rcdi"; };
} {
  name = "Fontconfig_jll";
  uuid = "a3f928ae-7b40-5064-980b-68af3947d34b";
  path = "F/Fontconfig_jll";
  replaceUrlInManifest = null;
  treehash = "21efd19106a55620a188615da6d3d06cd7f6ee03";
  artifacts = {
    "387d89822da323c098aba6f8ab316874d4e90f2e" = [{
      name = "Fontconfig";
      url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.93+0/Fontconfig.v2.13.93.x86_64-linux-gnu.tar.gz";
      sha256 = "e11e34977807b958fe5e7cea59a8354d94e11a052bad1348768aba8143769ea1";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl.git"; rev = "21efd19106a55620a188615da6d3d06cd7f6ee03"; sha256 = "1p6mfci77bp31w3xzlwhjccln40g6g2rdpfp38v5xf8sz2aybpw2"; };
} {
  name = "Formatting";
  uuid = "59287772-0a20-5a39-b81b-1366585eb4c0";
  path = "F/Formatting";
  replaceUrlInManifest = null;
  treehash = "8339d61043228fdd3eb658d86c926cb282ae72a8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/Formatting.jl.git"; rev = "8339d61043228fdd3eb658d86c926cb282ae72a8"; sha256 = "0ma3q9my51rr38bb5712xkc4h3rq0wsfjb4ac6mdh9ywn8rqvrmh"; };
} {
  name = "FreeType2_jll";
  uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7";
  path = "F/FreeType2_jll";
  replaceUrlInManifest = null;
  treehash = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9";
  artifacts = {
    "54c97eb1b0a6f74bac96297a815ddec2204a7db7" = [{
      name = "FreeType2";
      url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.4+0/FreeType2.v2.10.4.x86_64-linux-gnu.tar.gz";
      sha256 = "a3001f52ad6509380c1a36e7dfbaf100e362f9e9634dc7fe44d476710cb31f59";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl.git"; rev = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9"; sha256 = "03lgmb59lipc3bi7z22j4a53bbjmcwkf0xzpwan889p1ix3ry1lr"; };
} {
  name = "FriBidi_jll";
  uuid = "559328eb-81f9-559d-9380-de523a88c83c";
  path = "F/FriBidi_jll";
  replaceUrlInManifest = null;
  treehash = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91";
  artifacts = {
    "d11639e2a53726f2593e25ba98ed7b416f62bbc5" = [{
      name = "FriBidi";
      url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.10+0/FriBidi.v1.0.10.x86_64-linux-gnu.tar.gz";
      sha256 = "e0a3934f68e2a6c24cd1475e989219dbffbd31c3042c916df9a8f7877aa0aaec";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl.git"; rev = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91"; sha256 = "0vwgv4hdf4i70614yv17xs64n2l4407jn0lblvpkkwgpzzmh933a"; };
} {
  name = "GLFW_jll";
  uuid = "0656b61e-2033-5cc2-a64a-77c0f6c09b89";
  path = "G/GLFW_jll";
  replaceUrlInManifest = null;
  treehash = "d972031d28c8c8d9d7b41a536ad7bb0c2579caca";
  artifacts = {
    "5aa80c7b8e919cbfee41019069d9b25269befe10" = [{
      name = "GLFW";
      url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.x86_64-linux-gnu.tar.gz";
      sha256 = "77914b7ba66ccb288a018f1fba65ec8c383e17519732c23ef36fcc2adfb179eb";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl.git"; rev = "d972031d28c8c8d9d7b41a536ad7bb0c2579caca"; sha256 = "1r5hi5r82sjsrllqrfpawm41gpyjqiif9fzcfcj6bkww9wpjb3xh"; };
} {
  name = "GR";
  uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71";
  path = "G/GR";
  replaceUrlInManifest = null;
  treehash = "051072ff2accc6e0e87b708ddee39b18aa04a0bc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/jheinen/GR.jl.git"; rev = "051072ff2accc6e0e87b708ddee39b18aa04a0bc"; sha256 = "0lxqfdznbqqf373hl4r4zafak2hp6y901ds0287lggvsfkia1sd1"; };
} {
  name = "GR_jll";
  uuid = "d2c73de3-f751-5644-a686-071e5b155ba9";
  path = "G/GR_jll";
  replaceUrlInManifest = null;
  treehash = "501a4bf76fd679e7fcd678725d5072177392e756";
  artifacts = {
    "ba11969bdd27bbb55be64bfadc0de51a013e945a" = [{
      name = "GR";
      url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.71.1+0/GR.v0.71.1.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "65578443ec589e3f8bb0e98e52705c8523809c6d99039835ca4cd2e3b504047a";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl.git"; rev = "501a4bf76fd679e7fcd678725d5072177392e756"; sha256 = "19l2za78z56apx1jpdfylrdam131a1gzhxj79zcv7h1aybhy5v37"; };
} {
  name = "Gettext_jll";
  uuid = "78b55507-aeef-58d4-861c-77aaff3498b1";
  path = "G/Gettext_jll";
  replaceUrlInManifest = null;
  treehash = "9b02998aba7bf074d14de89f9d37ca24a1a0b046";
  artifacts = {
    "dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac" = [{
      name = "Gettext";
      url = "https://github.com/JuliaBinaryWrappers/Gettext_jll.jl/releases/download/Gettext-v0.21.0+0/Gettext.v0.21.0.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "fe332b26fb1303882a2d3b630048f5901d58510cdc12296eef963976a55b920b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Gettext_jll.jl.git"; rev = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"; sha256 = "0ghwkwv970q6j9ggkl0zlyrflhx8rd39y5i2zkc6p26084kyrxmf"; };
} {
  name = "Glib_jll";
  uuid = "7746bdde-850d-59dc-9ae8-88ece973131d";
  path = "G/Glib_jll";
  replaceUrlInManifest = null;
  treehash = "fb83fbe02fe57f2c068013aa94bcdf6760d3a7a7";
  artifacts = {
    "303fe895f57042ea41055187ec4af6322989b5cc" = [{
      name = "Glib";
      url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.74.0+1/Glib.v2.74.0.x86_64-linux-gnu.tar.gz";
      sha256 = "f4f5da008d1be204d5d450f6bb8156a6b9bc52211630d5e070ccfe37aea5be79";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl.git"; rev = "fb83fbe02fe57f2c068013aa94bcdf6760d3a7a7"; sha256 = "1xrzhdhipl12zqsfq5xsjvr7dqlgn5d7npmlqvf612nr567250d5"; };
} {
  name = "Graphite2_jll";
  uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472";
  path = "G/Graphite2_jll";
  replaceUrlInManifest = null;
  treehash = "344bf40dcab1073aca04aa0df4fb092f920e4011";
  artifacts = {
    "62c010876222f83fe8878bf2af0e362083d20ee3" = [{
      name = "Graphite2";
      url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/releases/download/Graphite2-v1.3.14+0/Graphite2.v1.3.14.x86_64-linux-gnu.tar.gz";
      sha256 = "16b4532bdb986aabf57d044c576d959dd05eb938a5b8b4e63c25dbdd7b0be55e";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl.git"; rev = "344bf40dcab1073aca04aa0df4fb092f920e4011"; sha256 = "0nm7bdm079nawsmnwwbpwmrbmnrb5gzy8c2lnp6ysb0f6bmzkypc"; };
} {
  name = "Grisu";
  uuid = "42e2da0e-8278-4e71-bc24-59509adca0fe";
  path = "G/Grisu";
  replaceUrlInManifest = null;
  treehash = "53bb909d1151e57e2484c3d1b53e19552b887fb2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaAttic/Grisu.jl.git"; rev = "53bb909d1151e57e2484c3d1b53e19552b887fb2"; sha256 = "0kmaavxxgxm47b8cj27s9rfsxxz8x4ic1ri1p0x1gmlmb6v00qf1"; };
} {
  name = "HTTP";
  uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3";
  path = "H/HTTP";
  replaceUrlInManifest = null;
  treehash = "e1acc37ed078d99a714ed8376446f92a5535ca65";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/HTTP.jl.git"; rev = "e1acc37ed078d99a714ed8376446f92a5535ca65"; sha256 = "0qcfixsq65g8hdimygam7cd8nvcz6w7nzkkjk98mvf65dcby4593"; };
} {
  name = "HarfBuzz_jll";
  uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566";
  path = "H/HarfBuzz_jll";
  replaceUrlInManifest = null;
  treehash = "129acf094d168394e80ee1dc4bc06ec835e510a3";
  artifacts = {
    "ee20a84d0166c074dfa736b642902dd87b4da48d" = [{
      name = "HarfBuzz";
      url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v2.8.1+1/HarfBuzz.v2.8.1.x86_64-linux-gnu.tar.gz";
      sha256 = "94808caccb9ad75549a807ee15d558457e92abd536d9ad1e0ce83a70e5e6674c";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl.git"; rev = "129acf094d168394e80ee1dc4bc06ec835e510a3"; sha256 = "1qgpf21gag3iwzx5cxwhfqgrffm4f33hp3gwyj2n2fayndwhn7lz"; };
} {
  name = "IJulia";
  uuid = "7073ff75-c697-5162-941a-fcdaad2a7d2a";
  path = "I/IJulia";
  replaceUrlInManifest = null;
  treehash = "98ab633acb0fe071b671f6c1785c46cd70bb86bd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/IJulia.jl.git"; rev = "98ab633acb0fe071b671f6c1785c46cd70bb86bd"; sha256 = "0aa3wfzi7s1b07d5pjimxsb0svjiyzy2ylf0i1m889h8mnd9in0r"; };
} {
  name = "IniFile";
  uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f";
  path = "I/IniFile";
  replaceUrlInManifest = null;
  treehash = "f550e6e32074c939295eb5ea6de31849ac2c9625";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/IniFile.jl.git"; rev = "f550e6e32074c939295eb5ea6de31849ac2c9625"; sha256 = "1vmy7bjvf6dbjyh4366g14qh9q2k790mr2l6zzvz2iih2rs15r7f"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "InverseFunctions";
  uuid = "3587e190-3f89-42d0-90ee-14403ec27112";
  path = "I/InverseFunctions";
  replaceUrlInManifest = null;
  treehash = "49510dfcb407e572524ba94aeae2fced1f3feb0f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/InverseFunctions.jl.git"; rev = "49510dfcb407e572524ba94aeae2fced1f3feb0f"; sha256 = "05g9f6i735x7syfr56l4yf4fy71kgdisjc6cfxi4jkf46iq86a69"; };
} {
  name = "IrrationalConstants";
  uuid = "92d709cd-6900-40b7-9082-c6be49f344b6";
  path = "I/IrrationalConstants";
  replaceUrlInManifest = null;
  treehash = "7fd44fd4ff43fc60815f8e764c0f352b83c49151";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/IrrationalConstants.jl.git"; rev = "7fd44fd4ff43fc60815f8e764c0f352b83c49151"; sha256 = "1a007iyh26x67a1bj6fcz7pfxa43kn2v7jpmnz727jkk3xgppg2s"; };
} {
  name = "JLFzf";
  uuid = "1019f520-868f-41f5-a6de-eb00f4b6a39c";
  path = "J/JLFzf";
  replaceUrlInManifest = null;
  treehash = "f377670cda23b6b7c1c0b3893e37451c5c1a2185";
  artifacts = {};
  src = fetchgit { url = "https://github.com/Moelf/JLFzf.jl.git"; rev = "f377670cda23b6b7c1c0b3893e37451c5c1a2185"; sha256 = "194g4k1qzhp902pvzbr4yrrpf3kzxcln39bc9hpsx0ajsfqgpgfg"; };
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "abc9885a7ca2052a736a600f7fa66209f96506e1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "abc9885a7ca2052a736a600f7fa66209f96506e1"; sha256 = "0y8q96hc7rpmmbqqgwv3zs65l9rchzp7slzv12v9n96a1bfsq9hw"; };
} {
  name = "JSON";
  uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6";
  path = "J/JSON";
  replaceUrlInManifest = null;
  treehash = "3c837543ddb02250ef42f4738347454f95079d4e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/JSON.jl.git"; rev = "3c837543ddb02250ef42f4738347454f95079d4e"; sha256 = "1l2p852sxq6h5fif3dqshvbw17gb06jmq2nkr88spvp7s0n0nslz"; };
} {
  name = "JpegTurbo_jll";
  uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8";
  path = "J/JpegTurbo_jll";
  replaceUrlInManifest = null;
  treehash = "b53380851c6e6664204efb2e62cd24fa5c47e4ba";
  artifacts = {
    "8793267ae1f4b96f626caa27147aa0218389c30d" = [{
      name = "JpegTurbo";
      url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.2+0/JpegTurbo.v2.1.2.x86_64-linux-gnu.tar.gz";
      sha256 = "b0165d5627f929dc8254d3d73341b6a6b9ad1f73c825e24437f82fdd0241b9ab";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl.git"; rev = "b53380851c6e6664204efb2e62cd24fa5c47e4ba"; sha256 = "1h1py91hai67r34mc4gjxybizygbcfvajgrpln454hzawilhfsvv"; };
} {
  name = "LAME_jll";
  uuid = "c1c5ebd0-6772-5130-a774-d5fcae4a789d";
  path = "L/LAME_jll";
  replaceUrlInManifest = null;
  treehash = "f6250b16881adf048549549fba48b1161acdac8c";
  artifacts = {
    "e19f3bb2eef5fb956b672235ea5323b5be9a0626" = [{
      name = "LAME";
      url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.1+0/LAME.v3.100.1.x86_64-linux-gnu.tar.gz";
      sha256 = "c50316310f171fb28403127fdb32ddd1e2fad2c073d57520c98d599e36f4f935";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl.git"; rev = "f6250b16881adf048549549fba48b1161acdac8c"; sha256 = "06hxc3a0h53nls2p4y1r8fn4f7gnxp30m6j0q61ijir3y6rn1i03"; };
} {
  name = "LERC_jll";
  uuid = "88015f11-f218-50d7-93a8-a6af411a945d";
  path = "L/LERC_jll";
  replaceUrlInManifest = null;
  treehash = "bf36f528eec6634efc60d7ec062008f171071434";
  artifacts = {
    "694cae97bb3cbf8f1f73f2ecabd891602ccf1751" = [{
      name = "LERC";
      url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v3.0.0+1/LERC.v3.0.0.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "f2587cecbe5bd776d606e4bd0071a409a4fff3f380b99983e9493ca5a469ca69";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl.git"; rev = "bf36f528eec6634efc60d7ec062008f171071434"; sha256 = "07j56zzi4m0vlaf0ql867ppk6s41piip372vsn0i6bwd4wkn3ji2"; };
} {
  name = "LZO_jll";
  uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac";
  path = "L/LZO_jll";
  replaceUrlInManifest = null;
  treehash = "e5b909bcf985c5e2605737d2ce278ed791b89be6";
  artifacts = {
    "921a059ebce52878d7a7944c9c345327958d1f5b" = [{
      name = "LZO";
      url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl/releases/download/LZO-v2.10.1+0/LZO.v2.10.1.x86_64-linux-gnu.tar.gz";
      sha256 = "5cb8f8bd495d29a1ad888500312e2d5ba38ccf0980278b154051ad8bd0e6ad77";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/LZO_jll.jl.git"; rev = "e5b909bcf985c5e2605737d2ce278ed791b89be6"; sha256 = "1gy57znz3b6pk902vgdzlrwrxib0bcfl0zr1prinfbr9vfmiv1h0"; };
} {
  name = "LaTeXStrings";
  uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f";
  path = "L/LaTeXStrings";
  replaceUrlInManifest = null;
  treehash = "f2355693d6778a178ade15952b7ac47a4ff97996";
  artifacts = {};
  src = fetchgit { url = "https://github.com/stevengj/LaTeXStrings.jl.git"; rev = "f2355693d6778a178ade15952b7ac47a4ff97996"; sha256 = "0iijp96ca9mqg5skr6ps7q0lvqaa374lr2zkbbia5q6qgpq0j5ww"; };
} {
  name = "Latexify";
  uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316";
  path = "L/Latexify";
  replaceUrlInManifest = null;
  treehash = "ab9aa169d2160129beb241cb2750ca499b4e90e9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/korsbo/Latexify.jl.git"; rev = "ab9aa169d2160129beb241cb2750ca499b4e90e9"; sha256 = "0mmzdxa1d4m2105gp8mkgrh7xdf8d3n6hccf254ym00fn95kdyps"; };
} {
  name = "LibCURL";
  uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21";
  path = "L/LibCURL";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibCURL_jll";
  uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0";
  path = "L/LibCURL_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibSSH2_jll";
  uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8";
  path = "L/LibSSH2_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libffi_jll";
  uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490";
  path = "L/Libffi_jll";
  replaceUrlInManifest = null;
  treehash = "0b4a5d71f3e5200a7dff793393e09dfc2d874290";
  artifacts = {
    "d00220164876dea2cb19993200662745eed5e2db" = [{
      name = "Libffi";
      url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+1/Libffi.v3.2.2.x86_64-linux-gnu.tar.gz";
      sha256 = "05e71ac9ed09bf3e5fb16ddc694dc6174a7554b4c5990e3d9502b5439ae7483d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl.git"; rev = "0b4a5d71f3e5200a7dff793393e09dfc2d874290"; sha256 = "04g5j7yjxdlv21ymrvka010k1z6m69p4jdcl4h5jqhbvgbll83kg"; };
} {
  name = "Libgcrypt_jll";
  uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4";
  path = "L/Libgcrypt_jll";
  replaceUrlInManifest = null;
  treehash = "64613c82a59c120435c067c2b809fc61cf5166ae";
  artifacts = {
    "92111ef825c608ea220f8e679dd8d908d7ac5b83" = [{
      name = "Libgcrypt";
      url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.8.7+0/Libgcrypt.v1.8.7.x86_64-linux-gnu.tar.gz";
      sha256 = "13850a69474b803d52f949658448aa79afd6c44c231575b2aff7ff52d09160e5";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl.git"; rev = "64613c82a59c120435c067c2b809fc61cf5166ae"; sha256 = "06fsdwrfw3f4cdbg1ssswznvj8ar3w5w4vxxag1hacs14pxlm5gi"; };
} {
  name = "Libglvnd_jll";
  uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29";
  path = "L/Libglvnd_jll";
  replaceUrlInManifest = null;
  treehash = "6f73d1dd803986947b2c750138528a999a6c7733";
  artifacts = {
    "37dda4e57d9de95c99d1f8c6b3d8f4eca88c39a2" = [{
      name = "Libglvnd";
      url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.6.0+0/Libglvnd.v1.6.0.x86_64-linux-gnu.tar.gz";
      sha256 = "c73957bc110c5897ad10107acef40b0a5c2e53f248d4e389683fe289e8c6b19f";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl.git"; rev = "6f73d1dd803986947b2c750138528a999a6c7733"; sha256 = "0qgfaw0630rrs8dgaaj4s1qnrcpj758awi8jldr0y0bg6kcw065f"; };
} {
  name = "Libgpg_error_jll";
  uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8";
  path = "L/Libgpg_error_jll";
  replaceUrlInManifest = null;
  treehash = "c333716e46366857753e273ce6a69ee0945a6db9";
  artifacts = {
    "16154f990153825ec24b52aac11165df2084b9dc" = [{
      name = "Libgpg_error";
      url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl/releases/download/Libgpg_error-v1.42.0+0/Libgpg_error.v1.42.0.x86_64-linux-gnu.tar.gz";
      sha256 = "0e9750caf43757872e2bf4c4fa363b1e597913f34ff2306f97652e1c3bc47313";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libgpg_error_jll.jl.git"; rev = "c333716e46366857753e273ce6a69ee0945a6db9"; sha256 = "0jmsn0mhn6b35b5awbrlpjjszknsplr62li574fkgwfxlfixb8iy"; };
} {
  name = "Libiconv_jll";
  uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531";
  path = "L/Libiconv_jll";
  replaceUrlInManifest = null;
  treehash = "42b62845d70a619f063a7da093d995ec8e15e778";
  artifacts = {
    "2e8fae88dcadc37883e31246fe7397f4f1039f88" = [{
      name = "Libiconv";
      url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.1+1/Libiconv.v1.16.1.x86_64-linux-gnu.tar.gz";
      sha256 = "e18d629395053b66a74d224eaf8db05c93573d9abfa8ae814ec6c31e128f237c";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl.git"; rev = "42b62845d70a619f063a7da093d995ec8e15e778"; sha256 = "0crwl7jl11q4mad6hbmpwfdx9gvr2nr27dj7hzia553wdsjs8kxb"; };
} {
  name = "Libmount_jll";
  uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9";
  path = "L/Libmount_jll";
  replaceUrlInManifest = null;
  treehash = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73";
  artifacts = {
    "5a508a62784097dab7c7ae5805f2c89d2cc97397" = [{
      name = "Libmount";
      url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.35.0+0/Libmount.v2.35.0.x86_64-linux-gnu.tar.gz";
      sha256 = "1db5da71d47f0284a7ad7fe3eb0faf481649e89015a9d5c31da340e9170b1b0d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl.git"; rev = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73"; sha256 = "04i4vm5rshz8nfmnxqx8rm3b9jd7b1xdiriac1bpsx3n0qf4pw89"; };
} {
  name = "Libtiff_jll";
  uuid = "89763e89-9b03-5906-acba-b20f662cd828";
  path = "L/Libtiff_jll";
  replaceUrlInManifest = null;
  treehash = "3eb79b0ca5764d4799c06699573fd8f533259713";
  artifacts = {
    "b610fc4e040c9a46c250ea4792cc64098003578a" = [{
      name = "Libtiff";
      url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl/releases/download/Libtiff-v4.4.0+0/Libtiff.v4.4.0.x86_64-linux-gnu.tar.gz";
      sha256 = "5a48156ffff6f8a58e469318d362007225bb74ee8e0f99152b0b8c2a560d0fc7";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl.git"; rev = "3eb79b0ca5764d4799c06699573fd8f533259713"; sha256 = "05nsjs29dmc2nxd5j95fgwk607a96d98181c5g339ysqbzgmmr21"; };
} {
  name = "Libuuid_jll";
  uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700";
  path = "L/Libuuid_jll";
  replaceUrlInManifest = null;
  treehash = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066";
  artifacts = {
    "2b77b304b0975d15bd5aeb4d1d5097ac6256ea3c" = [{
      name = "Libuuid";
      url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.36.0+0/Libuuid.v2.36.0.x86_64-linux-gnu.tar.gz";
      sha256 = "b541ec7a6ebf63916be7142507a363d744e9ed138138272e5bf08774899e866d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl.git"; rev = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066"; sha256 = "0iz1qrrpl8sp336m1f884sdgwbdlkp9sm371cwcfq4iriaihbmbs"; };
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LogExpFunctions";
  uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688";
  path = "L/LogExpFunctions";
  replaceUrlInManifest = null;
  treehash = "946607f84feb96220f480e0422d3484c49c00239";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/LogExpFunctions.jl.git"; rev = "946607f84feb96220f480e0422d3484c49c00239"; sha256 = "0kna18q7c6755vzsb15xwiklhg0byf9lisc92haz4ibks0zbcz61"; };
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LoggingExtras";
  uuid = "e6f89c97-d47a-5376-807f-9c37f3926c36";
  path = "L/LoggingExtras";
  replaceUrlInManifest = null;
  treehash = "cedb76b37bc5a6c702ade66be44f831fa23c681e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLogging/LoggingExtras.jl.git"; rev = "cedb76b37bc5a6c702ade66be44f831fa23c681e"; sha256 = "0mc0bbr2wsa809q74hg4npdw2xcni4xl40zz50i6djwnxq88yl07"; };
} {
  name = "MacroTools";
  uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09";
  path = "M/MacroTools";
  replaceUrlInManifest = null;
  treehash = "42324d08725e200c23d4dfb549e0d5d89dede2d2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/FluxML/MacroTools.jl.git"; rev = "42324d08725e200c23d4dfb549e0d5d89dede2d2"; sha256 = "1236z6hqqjz5rx19zgib3yghsc8xxr1fcgx83xrbv39n0za8msx8"; };
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS";
  uuid = "739be429-bea8-5141-9913-cc70e7f3736d";
  path = "M/MbedTLS";
  replaceUrlInManifest = null;
  treehash = "03a9b9718f5682ecb107ac9f7308991db4ce395b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/MbedTLS.jl.git"; rev = "03a9b9718f5682ecb107ac9f7308991db4ce395b"; sha256 = "10h8319ijlmck8qm8nhmlwl29d5nc6wk8s5rair1ragmpvzj6isz"; };
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Measures";
  uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e";
  path = "M/Measures";
  replaceUrlInManifest = null;
  treehash = "c13304c81eec1ed3af7fc20e75fb6b26092a1102";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/Measures.jl.git"; rev = "c13304c81eec1ed3af7fc20e75fb6b26092a1102"; sha256 = "1xbvypq36jj7795wzjs1yppzaa0bqnm66a6zcr6i5b8bc79cl2bw"; };
} {
  name = "Missings";
  uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28";
  path = "M/Missings";
  replaceUrlInManifest = null;
  treehash = "bf210ce90b6c9eed32d25dbcae1ebc565df2687f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Missings.jl.git"; rev = "bf210ce90b6c9eed32d25dbcae1ebc565df2687f"; sha256 = "1k481rm5lahmjyh34j177d4n10svgr0wm7ps5m3ar3xx6nr26ad5"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MozillaCACerts_jll";
  uuid = "14a3606d-f60d-562e-9121-12d972cd8159";
  path = "M/MozillaCACerts_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "NaNMath";
  uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3";
  path = "N/NaNMath";
  replaceUrlInManifest = null;
  treehash = "a7c3d1da1189a1c2fe843a3bfa04d18d20eb3211";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mlubin/NaNMath.jl.git"; rev = "a7c3d1da1189a1c2fe843a3bfa04d18d20eb3211"; sha256 = "0jharx6a3apsjab2j1y1w71j1n2vvdbcgjs2mblqvg59k06sq17b"; };
} {
  name = "NetworkOptions";
  uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908";
  path = "N/NetworkOptions";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Ogg_jll";
  uuid = "e7412a2a-1a6e-54c0-be00-318e2571c051";
  path = "O/Ogg_jll";
  replaceUrlInManifest = null;
  treehash = "887579a3eb005446d514ab7aeac5d1d027658b8f";
  artifacts = {
    "0631e2a6a31b5692eec7a575836451b16b734ec0" = [{
      name = "Ogg";
      url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl/releases/download/Ogg-v1.3.5+1/Ogg.v1.3.5.x86_64-linux-gnu.tar.gz";
      sha256 = "313ec9c6468b651bbdaa1035e57a960f51ef0f09ad48b7c4292aa22aa1a4ae9b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Ogg_jll.jl.git"; rev = "887579a3eb005446d514ab7aeac5d1d027658b8f"; sha256 = "0qxjbk48j9740n57lnz3d2zmb61j0lgy1gknaszkjxknsg5nxmxn"; };
} {
  name = "OpenBLAS_jll";
  uuid = "4536629a-c528-5b80-bd46-f80d51c5b363";
  path = "O/OpenBLAS_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "OpenLibm_jll";
  uuid = "05823500-19ac-5b8b-9628-191a04bc5112";
  path = "O/OpenLibm_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "OpenSSL";
  uuid = "4d8831e6-92b7-49fb-bdf8-b643e874388c";
  path = "O/OpenSSL";
  replaceUrlInManifest = null;
  treehash = "df6830e37943c7aaa10023471ca47fb3065cc3c4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/OpenSSL.jl.git"; rev = "df6830e37943c7aaa10023471ca47fb3065cc3c4"; sha256 = "090skd88zz57j8jymgswfdhfrnqvp2xbzwy4xyfa95mnvjla7q4s"; };
} {
  name = "OpenSSL_jll";
  uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95";
  path = "O/OpenSSL_jll";
  replaceUrlInManifest = null;
  treehash = "f6e9dba33f9f2c44e08a020b0caf6903be540004";
  artifacts = {
    "53037ac9d528ee46c3526799b407ee52b7c224f3" = [{
      name = "OpenSSL";
      url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v1.1.19+0/OpenSSL.v1.1.19.x86_64-linux-gnu.tar.gz";
      sha256 = "f479f537c1f41e66876f87476234c549c324b67532dbb4c0316947a1ae35a5d0";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl.git"; rev = "f6e9dba33f9f2c44e08a020b0caf6903be540004"; sha256 = "1v2fcqmny3xs341yhcvrrhkvldlvs7y0f1w934apy2fd7h6lw0xm"; };
} {
  name = "OpenSpecFun_jll";
  uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e";
  path = "O/OpenSpecFun_jll";
  replaceUrlInManifest = null;
  treehash = "13652491f6856acfd2db29360e1bbcd4565d04f1";
  artifacts = {
    "abf4b5086b4eb867021118c85b2cc11a15b764a9" = [{
      name = "OpenSpecFun";
      url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.5+0/OpenSpecFun.v0.5.5.x86_64-linux-gnu-libgfortran5.tar.gz";
      sha256 = "320e4c5ac643a4994de91e6a708973d8944a4413385e0ba7d2f5756276cd53cb";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl.git"; rev = "13652491f6856acfd2db29360e1bbcd4565d04f1"; sha256 = "0i878ws2si7ic5y8bsb0sndwgjjw5mnvg8xlqgyvl79nd28k2pj8"; };
} {
  name = "Opus_jll";
  uuid = "91d4177d-7536-5919-b921-800302f37372";
  path = "O/Opus_jll";
  replaceUrlInManifest = null;
  treehash = "51a08fb14ec28da2ec7a927c4337e4332c2a4720";
  artifacts = {
    "eff86eedadb59cff1a61399e3242b3f529ca6f59" = [{
      name = "Opus";
      url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.2+0/Opus.v1.3.2.x86_64-linux-gnu.tar.gz";
      sha256 = "d98994f57c751cfc382033e8fbc6545ac72a205577afa43dcc99f2a83402cc4f";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl.git"; rev = "51a08fb14ec28da2ec7a927c4337e4332c2a4720"; sha256 = "1f5iawfd0dn1bqvqs1lcandcfnr3z29d90vcark7bi3x89c877a8"; };
} {
  name = "OrderedCollections";
  uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d";
  path = "O/OrderedCollections";
  replaceUrlInManifest = null;
  treehash = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"; rev = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"; sha256 = "0jaxcmvkp8zpqrz101yikdigz90s70i7in5wn8kybwzf0na3lhwf"; };
} {
  name = "PCRE2_jll";
  uuid = "efcefdf7-47ab-520b-bdef-62a2eaa19f15";
  path = "P/PCRE2_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Parsers";
  uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0";
  path = "P/Parsers";
  replaceUrlInManifest = null;
  treehash = "b64719e8b4504983c7fca6cc9db3ebc8acc2a4d6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Parsers.jl.git"; rev = "b64719e8b4504983c7fca6cc9db3ebc8acc2a4d6"; sha256 = "1zzg594q862qvpaww8689hvianbi8li944jyqfbwmjinhl7nj7qd"; };
} {
  name = "Pipe";
  uuid = "b98c9c47-44ae-5843-9183-064241ee97a0";
  path = "P/Pipe";
  replaceUrlInManifest = null;
  treehash = "6842804e7867b115ca9de748a0cf6b364523c16d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/oxinabox/Pipe.jl.git"; rev = "6842804e7867b115ca9de748a0cf6b364523c16d"; sha256 = "01anm76nfmcajcbr2piji0rknisf5wwhimfndwaadkqkcjv7k4xn"; };
} {
  name = "Pixman_jll";
  uuid = "30392449-352a-5448-841d-b1acce4e97dc";
  path = "P/Pixman_jll";
  replaceUrlInManifest = null;
  treehash = "b4f5d02549a10e20780a24fce72bea96b6329e29";
  artifacts = {
    "f3337de0321b3370b90643d18bf63bd4ee79c991" = [{
      name = "Pixman";
      url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.40.1+0/Pixman.v0.40.1.x86_64-linux-gnu.tar.gz";
      sha256 = "6801be29d1a591c96af5f4bf53a3d06ca2a777a21661f704936a66a26f219bfc";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl.git"; rev = "b4f5d02549a10e20780a24fce72bea96b6329e29"; sha256 = "0ahawpgsiccmpa7gyxny7hq058igqvpza7ybqa44vl2nynnry2g7"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "PlotThemes";
  uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a";
  path = "P/PlotThemes";
  replaceUrlInManifest = null;
  treehash = "1f03a2d339f42dca4a4da149c7e15e9b896ad899";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPlots/PlotThemes.jl.git"; rev = "1f03a2d339f42dca4a4da149c7e15e9b896ad899"; sha256 = "1wyqbl43v5ia9cp8pkik4865hzzwd4rlkg1iyi60ss0gqacnpf01"; };
} {
  name = "PlotUtils";
  uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043";
  path = "P/PlotUtils";
  replaceUrlInManifest = null;
  treehash = "21303256d239f6b484977314674aef4bb1fe4420";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPlots/PlotUtils.jl.git"; rev = "21303256d239f6b484977314674aef4bb1fe4420"; sha256 = "016r4nck4c7vwl2bbmirgcwdnmmrc2r84avj1irrny59sz5bhsks"; };
} {
  name = "Plots";
  uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80";
  path = "P/Plots";
  replaceUrlInManifest = null;
  treehash = "6a9521b955b816aa500462951aa67f3e4467248a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPlots/Plots.jl.git"; rev = "6a9521b955b816aa500462951aa67f3e4467248a"; sha256 = "0hicfyncyjk23yj84g7v5rcdfgp1j1ycwpjmdx502jjpphyn6xnb"; };
} {
  name = "Preferences";
  uuid = "21216c6a-2e73-6563-6e65-726566657250";
  path = "P/Preferences";
  replaceUrlInManifest = null;
  treehash = "47e5f437cc0e7ef2ce8406ce1e7e24d44915f88d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Preferences.jl.git"; rev = "47e5f437cc0e7ef2ce8406ce1e7e24d44915f88d"; sha256 = "1fa9s1rhq84gwgprl2508lfgm1avhck5grbqscbp9fd7snl4zff4"; };
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Qt5Base_jll";
  uuid = "ea2cea3b-5b76-57ae-a6ef-0a8af62496e1";
  path = "Q/Qt5Base_jll";
  replaceUrlInManifest = null;
  treehash = "0c03844e2231e12fda4d0086fd7cbe4098ee8dc5";
  artifacts = {
    "388246ba5e10de0b457ad8a6a855a6603afc7378" = [{
      name = "Qt5Base";
      url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl/releases/download/Qt5Base-v5.15.3+2/Qt5Base.v5.15.3.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "4a94d0efdd92d63f073a4f7a40cce8e97f0b354d73c894dff7b73f347a9f55db";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Qt5Base_jll.jl.git"; rev = "0c03844e2231e12fda4d0086fd7cbe4098ee8dc5"; sha256 = "09a13w8jqkv3hac9fk3i9p0z4yxy3cqig0967avyp51sdgl0fbvz"; };
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "RecipesBase";
  uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01";
  path = "R/RecipesBase";
  replaceUrlInManifest = null;
  treehash = "d12e612bba40d189cead6ff857ddb67bd2e6a387";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPlots/Plots.jl.git"; rev = "d12e612bba40d189cead6ff857ddb67bd2e6a387"; sha256 = "1nlgrp2n7pnzha1fcfl3sb5rzch0f4qc7lsczr2rmwg8m2f7045q"; };
} {
  name = "RecipesPipeline";
  uuid = "01d81517-befc-4cb6-b9ec-a95719d0359c";
  path = "R/RecipesPipeline";
  replaceUrlInManifest = null;
  treehash = "e974477be88cb5e3040009f3767611bc6357846f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPlots/Plots.jl.git"; rev = "e974477be88cb5e3040009f3767611bc6357846f"; sha256 = "1m114ys5hxmydplycmm0x649jwrg8d10j9jhvg4hhyspxwniknql"; };
} {
  name = "Reexport";
  uuid = "189a3867-3050-52da-a836-e630ba90ab69";
  path = "R/Reexport";
  replaceUrlInManifest = null;
  treehash = "45e428421666073eab6f2da5c9d310d99bb12f9b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/simonster/Reexport.jl.git"; rev = "45e428421666073eab6f2da5c9d310d99bb12f9b"; sha256 = "0inf5q6f01ncd5c5wm8mwzv2hs627ng6xlh8dhrlflp321hbamwf"; };
} {
  name = "RelocatableFolders";
  uuid = "05181044-ff0b-4ac5-8273-598c1e38db00";
  path = "R/RelocatableFolders";
  replaceUrlInManifest = null;
  treehash = "90bc7a7c96410424509e4263e277e43250c05691";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/RelocatableFolders.jl.git"; rev = "90bc7a7c96410424509e4263e277e43250c05691"; sha256 = "0w9ayhr4r5g39csd87c2fa23vww1akxamx7aj9aql2cxndpdaxqk"; };
} {
  name = "Requires";
  uuid = "ae029012-a4dd-5104-9daa-d747884805df";
  path = "R/Requires";
  replaceUrlInManifest = null;
  treehash = "838a3a4188e2ded87a4f9f184b4b0d78a1e91cb7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Requires.jl.git"; rev = "838a3a4188e2ded87a4f9f184b4b0d78a1e91cb7"; sha256 = "0gmqs7f17aq500lbdff4ibws00f8m0pnzskvf4b3ig520xv3n3nm"; };
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Scratch";
  uuid = "6c6a2e73-6563-6170-7368-637461726353";
  path = "S/Scratch";
  replaceUrlInManifest = null;
  treehash = "f94f779c94e58bf9ea243e77a37e16d9de9126bd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Scratch.jl.git"; rev = "f94f779c94e58bf9ea243e77a37e16d9de9126bd"; sha256 = "0s7dmqsskq5vy7sk6pxng5vrznrn6msg7xf8a9kj3a03b617pgap"; };
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Showoff";
  uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f";
  path = "S/Showoff";
  replaceUrlInManifest = null;
  treehash = "91eddf657aca81df9ae6ceb20b959ae5653ad1de";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/Showoff.jl.git"; rev = "91eddf657aca81df9ae6ceb20b959ae5653ad1de"; sha256 = "1064k83dnnyqz62xiby4gbhy9fjsdwn7hn20m75xpswflj1rvqz7"; };
} {
  name = "SimpleBufferStream";
  uuid = "777ac1f9-54b0-4bf8-805c-2214025038e7";
  path = "S/SimpleBufferStream";
  replaceUrlInManifest = null;
  treehash = "874e8867b33a00e784c8a7e4b60afe9e037b74e1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/staticfloat/SimpleBufferStream.jl.git"; rev = "874e8867b33a00e784c8a7e4b60afe9e037b74e1"; sha256 = "075abmq14pxld9447568f5alyyjs27ns1iq6b95w5yp1i29ph9d2"; };
} {
  name = "SnoopPrecompile";
  uuid = "66db9d55-30c0-4569-8b51-7e840670fc0c";
  path = "S/SnoopPrecompile";
  replaceUrlInManifest = null;
  treehash = "f604441450a3c0569830946e5b33b78c928e1a85";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/SnoopCompile.jl.git"; rev = "f604441450a3c0569830946e5b33b78c928e1a85"; sha256 = "01krnwnrnf6i70zi1h4cwchrv20kzr4lr05hc2j2m3r3waf4vz9h"; };
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SoftGlobalScope";
  uuid = "b85f4697-e234-5449-a836-ec8e2f98b302";
  path = "S/SoftGlobalScope";
  replaceUrlInManifest = null;
  treehash = "986ec2b6162ccb95de5892ed17832f95badf770c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/stevengj/SoftGlobalScope.jl.git"; rev = "986ec2b6162ccb95de5892ed17832f95badf770c"; sha256 = "1n3l0al1vw5jpb4k9a29a71666cdb617nmiqg34wcmyfzrxpvv39"; };
} {
  name = "SortingAlgorithms";
  uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c";
  path = "S/SortingAlgorithms";
  replaceUrlInManifest = null;
  treehash = "a4ada03f999bd01b3a25dcaa30b2d929fe537e00";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/SortingAlgorithms.jl.git"; rev = "a4ada03f999bd01b3a25dcaa30b2d929fe537e00"; sha256 = "0alrkng2z7b95pz93ap7jcwai35q05bl91nhr7whzz94ksxajb68"; };
} {
  name = "SparseArrays";
  uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SpecialFunctions";
  uuid = "276daf66-3868-5448-9aa4-cd146d93841b";
  path = "S/SpecialFunctions";
  replaceUrlInManifest = null;
  treehash = "d75bda01f8c31ebb72df80a46c88b25d1c79c56d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/SpecialFunctions.jl.git"; rev = "d75bda01f8c31ebb72df80a46c88b25d1c79c56d"; sha256 = "1bn2y19j9n0sxvv7yds9n99ibg0nfwvl6a2rw7wknqi3maln86f9"; };
} {
  name = "Statistics";
  uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "StatsAPI";
  uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0";
  path = "S/StatsAPI";
  replaceUrlInManifest = null;
  treehash = "f9af7f195fb13589dd2e2d57fdb401717d2eb1f6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsAPI.jl.git"; rev = "f9af7f195fb13589dd2e2d57fdb401717d2eb1f6"; sha256 = "0r10vfd802pfghid4apd5ssxl8d96lzz5sqsrfhqf4rsixrvjsy4"; };
} {
  name = "StatsBase";
  uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91";
  path = "S/StatsBase";
  replaceUrlInManifest = null;
  treehash = "d1bf48bfcc554a3761a133fe3a9bb01488e06916";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsBase.jl.git"; rev = "d1bf48bfcc554a3761a133fe3a9bb01488e06916"; sha256 = "1if1sajqfgyqqnjq0wxkc2m0mpzhvvrgn026ah7kl47kbx7xmiqr"; };
} {
  name = "TOML";
  uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76";
  path = "T/TOML";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Tar";
  uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e";
  path = "T/Tar";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TensorCore";
  uuid = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50";
  path = "T/TensorCore";
  replaceUrlInManifest = null;
  treehash = "1feb45f88d133a655e001435632f019a9a1bcdb6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/TensorCore.jl.git"; rev = "1feb45f88d133a655e001435632f019a9a1bcdb6"; sha256 = "1sy3in4a1rl3l2vk0cm9mzg2nkva7syhr7i35si0kbzhkdwpbqjy"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TranscodingStreams";
  uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa";
  path = "T/TranscodingStreams";
  replaceUrlInManifest = null;
  treehash = "8a75929dcd3c38611db2f8d08546decb514fcadf";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/TranscodingStreams.jl.git"; rev = "8a75929dcd3c38611db2f8d08546decb514fcadf"; sha256 = "0bfys5nhcvdda6785vc30jqmv6jzjwfx0m9kzzvcmklsdm6xblc5"; };
} {
  name = "URIs";
  uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4";
  path = "U/URIs";
  replaceUrlInManifest = null;
  treehash = "ac00576f90d8a259f2c9d823e91d1de3fd44d348";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/URIs.jl.git"; rev = "ac00576f90d8a259f2c9d823e91d1de3fd44d348"; sha256 = "1sd0f5zbp5inn845xbm2k97dcb4yixr3yp9f14dngd44by18p93v"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "UnicodeFun";
  uuid = "1cfade01-22cf-5700-b092-accc4b62d6e1";
  path = "U/UnicodeFun";
  replaceUrlInManifest = null;
  treehash = "53915e50200959667e78a92a418594b428dffddf";
  artifacts = {};
  src = fetchgit { url = "https://github.com/SimonDanisch/UnicodeFun.jl.git"; rev = "53915e50200959667e78a92a418594b428dffddf"; sha256 = "11hch4zpi8qby8pcqfvxnx88y45lxan4ind9kj2d0pgw614zkpg0"; };
} {
  name = "Unzip";
  uuid = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d";
  path = "U/Unzip";
  replaceUrlInManifest = null;
  treehash = "ca0969166a028236229f63514992fc073799bb78";
  artifacts = {};
  src = fetchgit { url = "https://github.com/bramtayl/Unzip.jl.git"; rev = "ca0969166a028236229f63514992fc073799bb78"; sha256 = "0i4rkvyd8br024s0sgs3crpi6za2f51m42whkx0jd22wiwg675vb"; };
} {
  name = "VersionParsing";
  uuid = "81def892-9a0e-5fdd-b105-ffc91e053289";
  path = "V/VersionParsing";
  replaceUrlInManifest = null;
  treehash = "58d6e80b4ee071f5efd07fda82cb9fbe17200868";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaInterop/VersionParsing.jl.git"; rev = "58d6e80b4ee071f5efd07fda82cb9fbe17200868"; sha256 = "0indw7xd1sg52g67x2330xdwmpkpq93cz6wdmw39r1plr5vplz7y"; };
} {
  name = "Wayland_jll";
  uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89";
  path = "W/Wayland_jll";
  replaceUrlInManifest = null;
  treehash = "3e61f0b86f90dacb0bc0e73a0c5a83f6a8636e23";
  artifacts = {
    "3c7eef5f322b19cd4b5db6b21f8cafda87b8b26c" = [{
      name = "Wayland";
      url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl/releases/download/Wayland-v1.19.0+0/Wayland.v1.19.0.x86_64-linux-gnu.tar.gz";
      sha256 = "aa89d78fa2dcd1c46055706848a152a8dab1c703b182a7f5d12290d961646f38";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Wayland_jll.jl.git"; rev = "3e61f0b86f90dacb0bc0e73a0c5a83f6a8636e23"; sha256 = "0rh3c2gy43611zqp4x74axd2yf2dhfqcqlx75iflzb29k7hwc2iq"; };
} {
  name = "Wayland_protocols_jll";
  uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91";
  path = "W/Wayland_protocols_jll";
  replaceUrlInManifest = null;
  treehash = "4528479aa01ee1b3b4cd0e6faef0e04cf16466da";
  artifacts = {
    "f42f9d226c70f0bc88e5f897d914d9de1ac2ce03" = [{
      name = "Wayland_protocols";
      url = "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl/releases/download/Wayland_protocols-v1.25.0+0/Wayland_protocols.v1.25.0.any.tar.gz";
      sha256 = "d1a84e0016d12f933a2ef390a0fa7db442df631c6c42a433c2b1c207f89f92f5";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Wayland_protocols_jll.jl.git"; rev = "4528479aa01ee1b3b4cd0e6faef0e04cf16466da"; sha256 = "1fsic4icbhf2ja035n7myz7wjghh9gw3knvmxww6p58f1800cl1r"; };
} {
  name = "XML2_jll";
  uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a";
  path = "X/XML2_jll";
  replaceUrlInManifest = null;
  treehash = "58443b63fb7e465a8a7210828c91c08b92132dff";
  artifacts = {
    "3e19866657986912870f596aecfee137473965a9" = [{
      name = "XML2";
      url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.9.14+0/XML2.v2.9.14.x86_64-linux-gnu.tar.gz";
      sha256 = "698f1f30c4e9e05a7563f62ec722877122243dd6f91df6363f00e233607eb52b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl.git"; rev = "58443b63fb7e465a8a7210828c91c08b92132dff"; sha256 = "1xk8smrjgz256as7wan28dyagfjz1z6j0rl0zq7fbqvzgyidqbw9"; };
} {
  name = "XSLT_jll";
  uuid = "aed1982a-8fda-507f-9586-7b0439959a61";
  path = "X/XSLT_jll";
  replaceUrlInManifest = null;
  treehash = "91844873c4085240b95e795f692c4cec4d805f8a";
  artifacts = {
    "f3ec73d7bf2f4419ba0943e94f7738cf56050797" = [{
      name = "XSLT";
      url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.34+0/XSLT.v1.1.34.x86_64-linux-gnu.tar.gz";
      sha256 = "e41b5251610babf93503931d2f3dfd05e1a462e8cad5246e6b58a96cf7ac341f";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl.git"; rev = "91844873c4085240b95e795f692c4cec4d805f8a"; sha256 = "0wjkfnrgpd7c6i4ga5xzsqqmfrxcdkr1kjsxmd9bff8cqvyknnhq"; };
} {
  name = "Xorg_libX11_jll";
  uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc";
  path = "X/Xorg_libX11_jll";
  replaceUrlInManifest = null;
  treehash = "5be649d550f3f4b95308bf0183b82e2582876527";
  artifacts = {
    "431a0e3706ffe717ab5d35c47bc38626c6169504" = [{
      name = "Xorg_libX11";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libX11_jll.jl/releases/download/Xorg_libX11-v1.6.9+3/Xorg_libX11.v1.6.9.x86_64-linux-gnu.tar.gz";
      sha256 = "07ece1dd93146db1f25b829eb895e769652eb97bf90725bdfbf07b8e4c4afab4";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libX11_jll.jl.git"; rev = "5be649d550f3f4b95308bf0183b82e2582876527"; sha256 = "0392bvhw810qa9aabkwklbi6wmhp481fks1bls0326rb97rachls"; };
} {
  name = "Xorg_libXau_jll";
  uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec";
  path = "X/Xorg_libXau_jll";
  replaceUrlInManifest = null;
  treehash = "4e490d5c960c314f33885790ed410ff3a94ce67e";
  artifacts = {
    "4487a7356408c3a92924e56f9d3891724855282c" = [{
      name = "Xorg_libXau";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+3/Xorg_libXau.v1.0.9.x86_64-linux-gnu.tar.gz";
      sha256 = "763b24fb4a12e0a7d22b3a8f2f90f72e35b37c90771d1dcdad0d2d1e69f36e71";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl.git"; rev = "4e490d5c960c314f33885790ed410ff3a94ce67e"; sha256 = "1kdqczwbm2h5m5ikrdjkmhfhn7z75nflcqqc8algm7w2r7a81mn8"; };
} {
  name = "Xorg_libXcursor_jll";
  uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724";
  path = "X/Xorg_libXcursor_jll";
  replaceUrlInManifest = null;
  treehash = "12e0eb3bc634fa2080c1c37fccf56f7c22989afd";
  artifacts = {
    "05616da88f6b36c7c94164d4070776aef18ce46b" = [{
      name = "Xorg_libXcursor";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+3/Xorg_libXcursor.v1.2.0.x86_64-linux-gnu.tar.gz";
      sha256 = "f7352a518bad4916015c1ad87949771d27e5e2fe12d50da73ac8ebf036c575cb";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl.git"; rev = "12e0eb3bc634fa2080c1c37fccf56f7c22989afd"; sha256 = "1rrj13n5747aqxr204zv81r9dvafl94b6nr7gdjhgpywxr2gzq6g"; };
} {
  name = "Xorg_libXdmcp_jll";
  uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05";
  path = "X/Xorg_libXdmcp_jll";
  replaceUrlInManifest = null;
  treehash = "4fe47bd2247248125c428978740e18a681372dd4";
  artifacts = {
    "51c48c945ae76d6c0102649044d9976d93b78125" = [{
      name = "Xorg_libXdmcp";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl/releases/download/Xorg_libXdmcp-v1.1.3+3/Xorg_libXdmcp.v1.1.3.x86_64-linux-gnu.tar.gz";
      sha256 = "2692189b5fb2bdd90525a7bfbfa96e9fd65e6461d993bbfb1e575ca8614c0cd2";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXdmcp_jll.jl.git"; rev = "4fe47bd2247248125c428978740e18a681372dd4"; sha256 = "1ck5nfl6ry0hfp21vh88qgfwlpp9fp5nb74han5dsnhkksjp8z5h"; };
} {
  name = "Xorg_libXext_jll";
  uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3";
  path = "X/Xorg_libXext_jll";
  replaceUrlInManifest = null;
  treehash = "b7c0aa8c376b31e4852b360222848637f481f8c3";
  artifacts = {
    "fc6071b99b67da0ae4e49ebab70c369ce9a76c9e" = [{
      name = "Xorg_libXext";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl/releases/download/Xorg_libXext-v1.3.4+3/Xorg_libXext.v1.3.4.x86_64-linux-gnu.tar.gz";
      sha256 = "ad0719c30cc8d8a7339a52deb85114e5067b1443b4f20a6d37f8b7b47b8fd941";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXext_jll.jl.git"; rev = "b7c0aa8c376b31e4852b360222848637f481f8c3"; sha256 = "0h7d2020l48mb5cpi4jkm5hhhsha52anzvyvppk5a9j3zrqkfabv"; };
} {
  name = "Xorg_libXfixes_jll";
  uuid = "d091e8ba-531a-589c-9de9-94069b037ed8";
  path = "X/Xorg_libXfixes_jll";
  replaceUrlInManifest = null;
  treehash = "0e0dc7431e7a0587559f9294aeec269471c991a4";
  artifacts = {
    "f0d193662fead3500b523f94b4f1878daab59a93" = [{
      name = "Xorg_libXfixes";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl/releases/download/Xorg_libXfixes-v5.0.3+3/Xorg_libXfixes.v5.0.3.x86_64-linux-gnu.tar.gz";
      sha256 = "98bf6ed379dbad1a8829a99aef1ec131948ecd007e1e352330113b1452f6f1c7";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXfixes_jll.jl.git"; rev = "0e0dc7431e7a0587559f9294aeec269471c991a4"; sha256 = "1szda3jk92m1sdbb8afpnb1kg5m803vignnw8wlf03sfnzgs91hl"; };
} {
  name = "Xorg_libXi_jll";
  uuid = "a51aa0fd-4e3c-5386-b890-e753decda492";
  path = "X/Xorg_libXi_jll";
  replaceUrlInManifest = null;
  treehash = "89b52bc2160aadc84d707093930ef0bffa641246";
  artifacts = {
    "2df316da869cd97f7d70029428ee1e2e521407cd" = [{
      name = "Xorg_libXi";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl/releases/download/Xorg_libXi-v1.7.10+3/Xorg_libXi.v1.7.10.x86_64-linux-gnu.tar.gz";
      sha256 = "7febe8f377cb502bf72f97a5cd7aaec450b87c19feeab94f1a3b0345bea6f92a";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXi_jll.jl.git"; rev = "89b52bc2160aadc84d707093930ef0bffa641246"; sha256 = "0j6h1hvmwwwbnca7ar6nzpi52p2m9inyc0kgazgdwh2x8nz6p21f"; };
} {
  name = "Xorg_libXinerama_jll";
  uuid = "d1454406-59df-5ea1-beac-c340f2130bc3";
  path = "X/Xorg_libXinerama_jll";
  replaceUrlInManifest = null;
  treehash = "26be8b1c342929259317d8b9f7b53bf2bb73b123";
  artifacts = {
    "7190f0cb0832b80761cc6d513dd9b935f3e26358" = [{
      name = "Xorg_libXinerama";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl/releases/download/Xorg_libXinerama-v1.1.4+3/Xorg_libXinerama.v1.1.4.x86_64-linux-gnu.tar.gz";
      sha256 = "9e12fc7c4d8d41fad3d3d539e04c64ab651dd109a10fe0761352f321a6f9bed1";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXinerama_jll.jl.git"; rev = "26be8b1c342929259317d8b9f7b53bf2bb73b123"; sha256 = "0rzr0jgqxsw8m0yy3drazy5k72ni38agkmzx5ccnrwmiwjbmghbj"; };
} {
  name = "Xorg_libXrandr_jll";
  uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484";
  path = "X/Xorg_libXrandr_jll";
  replaceUrlInManifest = null;
  treehash = "34cea83cb726fb58f325887bf0612c6b3fb17631";
  artifacts = {
    "4daa3879a820580557ef34945e2ae243dfcbba11" = [{
      name = "Xorg_libXrandr";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+3/Xorg_libXrandr.v1.5.2.x86_64-linux-gnu.tar.gz";
      sha256 = "eb89f0c6d69ad486b5c3197609f57877b58f680a6beb6fd224dba1ecaf405994";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl.git"; rev = "34cea83cb726fb58f325887bf0612c6b3fb17631"; sha256 = "07xw2j59kw0p4ca6zia0afh219j9n2f5pa8lc9m2ijldhk3ddk17"; };
} {
  name = "Xorg_libXrender_jll";
  uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa";
  path = "X/Xorg_libXrender_jll";
  replaceUrlInManifest = null;
  treehash = "19560f30fd49f4d4efbe7002a1037f8c43d43b96";
  artifacts = {
    "527e66fb9b12dfd1f58157fe0b3fd52b84062432" = [{
      name = "Xorg_libXrender";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+3/Xorg_libXrender.v0.9.10.x86_64-linux-gnu.tar.gz";
      sha256 = "44f42b88ba7558a7916161c6d4c0e0c9e8ee328c5c5561d7ef9ab4130f6c92c5";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl.git"; rev = "19560f30fd49f4d4efbe7002a1037f8c43d43b96"; sha256 = "1w5nivmzv0hq0ypqh7z8vijmzwl4m1ffn7z3y74q7mwznh0vxwda"; };
} {
  name = "Xorg_libpthread_stubs_jll";
  uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74";
  path = "X/Xorg_libpthread_stubs_jll";
  replaceUrlInManifest = null;
  treehash = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb";
  artifacts = {
    "aa3e93661fefff04200a3d0099cfdd1b5fc0ded3" = [{
      name = "Xorg_libpthread_stubs";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+2/Xorg_libpthread_stubs.v0.1.0.x86_64-linux-gnu.tar.gz";
      sha256 = "8cba18f2080eb2cb0ee20447faa565b568f65c82505027fc558f34400e42bd0b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl.git"; rev = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb"; sha256 = "19p9yd0c3dlabh1n6fjka520r2w15gh2z9zdkg30sx26lxzi5fii"; };
} {
  name = "Xorg_libxcb_jll";
  uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b";
  path = "X/Xorg_libxcb_jll";
  replaceUrlInManifest = null;
  treehash = "daf17f441228e7a3833846cd048892861cff16d6";
  artifacts = {
    "5ba11d7fb2ceb4ca812844eb4af886a212b47f65" = [{
      name = "Xorg_libxcb";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+2/Xorg_libxcb.v1.13.0.x86_64-linux-gnu.tar.gz";
      sha256 = "643036861ad9b2a5555b281616ab44dbd506fe3e1bedc5933fefc79eeeabbb25";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl.git"; rev = "daf17f441228e7a3833846cd048892861cff16d6"; sha256 = "0bxsl2vh94rrnh7czq437j1kfdqiy91wpcgsn1yjf905fw0b9xvg"; };
} {
  name = "Xorg_libxkbfile_jll";
  uuid = "cc61e674-0454-545c-8b26-ed2c68acab7a";
  path = "X/Xorg_libxkbfile_jll";
  replaceUrlInManifest = null;
  treehash = "926af861744212db0eb001d9e40b5d16292080b2";
  artifacts = {
    "84f18b0f422f5d6a023fe871b59a9fc536d04f5c" = [{
      name = "Xorg_libxkbfile";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl/releases/download/Xorg_libxkbfile-v1.1.0+3/Xorg_libxkbfile.v1.1.0.x86_64-linux-gnu.tar.gz";
      sha256 = "a50f7cc06f1a4f609ddf97e22118e3813fcc6f9e2e9d3fe321f0c2a77c5ca379";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_libxkbfile_jll.jl.git"; rev = "926af861744212db0eb001d9e40b5d16292080b2"; sha256 = "1qpvwqqrs05rrcmsb4xgg3q85sxbrr3h343p2fbg34wdb45xahv0"; };
} {
  name = "Xorg_xcb_util_image_jll";
  uuid = "12413925-8142-5f55-bb0e-6d7ca50bb09b";
  path = "X/Xorg_xcb_util_image_jll";
  replaceUrlInManifest = null;
  treehash = "0fab0a40349ba1cba2c1da699243396ff8e94b97";
  artifacts = {
    "0d364e900393f710a03a5bafe2852d76e4d2c2cd" = [{
      name = "Xorg_xcb_util_image";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.0+1/Xorg_xcb_util_image.v0.4.0.x86_64-linux-gnu.tar.gz";
      sha256 = "f394b6bad5316f535149a43482945c997c7824e8c57b86145af2f1a41533ff53";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl.git"; rev = "0fab0a40349ba1cba2c1da699243396ff8e94b97"; sha256 = "1fa43fg231s0r19x5kgf4p1aigwpagp9b82in2q09g4lx5jbq475"; };
} {
  name = "Xorg_xcb_util_jll";
  uuid = "2def613f-5ad1-5310-b15b-b15d46f528f5";
  path = "X/Xorg_xcb_util_jll";
  replaceUrlInManifest = null;
  treehash = "e7fd7b2881fa2eaa72717420894d3938177862d1";
  artifacts = {
    "cacd8c147f866d6672e1aca9bb01fb919a81e96a" = [{
      name = "Xorg_xcb_util";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_jll.jl/releases/download/Xorg_xcb_util-v0.4.0+1/Xorg_xcb_util.v0.4.0.x86_64-linux-gnu.tar.gz";
      sha256 = "d0412e5205795f7b766d74f642211f629eba638f14fced7114e9bc49da3112d8";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_jll.jl.git"; rev = "e7fd7b2881fa2eaa72717420894d3938177862d1"; sha256 = "1kplfwgqji6zb7cmh6i6g5bhzb8mgq5jcggcihgmkngnbglh9zr0"; };
} {
  name = "Xorg_xcb_util_keysyms_jll";
  uuid = "975044d2-76e6-5fbe-bf08-97ce7c6574c7";
  path = "X/Xorg_xcb_util_keysyms_jll";
  replaceUrlInManifest = null;
  treehash = "d1151e2c45a544f32441a567d1690e701ec89b00";
  artifacts = {
    "79cc5446ced978de84b6e673e01da0ebfdd6e4a5" = [{
      name = "Xorg_xcb_util_keysyms";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+1/Xorg_xcb_util_keysyms.v0.4.0.x86_64-linux-gnu.tar.gz";
      sha256 = "2107c88a7ca42b4c8dec4c3d10dbb0d9c8e211a23e9549b6e99c76885ed164a7";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl.git"; rev = "d1151e2c45a544f32441a567d1690e701ec89b00"; sha256 = "01ngkr1zpmyldknry4d2k3sjcl7rq5ia0kxzwjs5hlnzq6wlgj09"; };
} {
  name = "Xorg_xcb_util_renderutil_jll";
  uuid = "0d47668e-0667-5a69-a72c-f761630bfb7e";
  path = "X/Xorg_xcb_util_renderutil_jll";
  replaceUrlInManifest = null;
  treehash = "dfd7a8f38d4613b6a575253b3174dd991ca6183e";
  artifacts = {
    "1a2adcee7d99fea18ead33c350332626b262e29a" = [{
      name = "Xorg_xcb_util_renderutil";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+1/Xorg_xcb_util_renderutil.v0.3.9.x86_64-linux-gnu.tar.gz";
      sha256 = "c5ee27039ff7d8b1d1b87537019294f066cbd7c7ce10eaac05a5a34c810aaa02";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl.git"; rev = "dfd7a8f38d4613b6a575253b3174dd991ca6183e"; sha256 = "0i4463d3vz4ikc7kkqf063syfar9gpiq895dq88cqz83z12z8msz"; };
} {
  name = "Xorg_xcb_util_wm_jll";
  uuid = "c22f9ab0-d5fe-5066-847c-f4bb1cd4e361";
  path = "X/Xorg_xcb_util_wm_jll";
  replaceUrlInManifest = null;
  treehash = "e78d10aab01a4a154142c5006ed44fd9e8e31b67";
  artifacts = {
    "b7dc5dce963737414a564aca8d4b82ee388f4fa1" = [{
      name = "Xorg_xcb_util_wm";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+1/Xorg_xcb_util_wm.v0.4.1.x86_64-linux-gnu.tar.gz";
      sha256 = "7750782a89322467dcf0ddea4c765bfc4c0aaf202c0ba29c84ac180b75033a43";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl.git"; rev = "e78d10aab01a4a154142c5006ed44fd9e8e31b67"; sha256 = "08bbk7nss8pr355jdkb9jnpqacv5ajzd6j4rb23hgvn8mh2yinjj"; };
} {
  name = "Xorg_xkbcomp_jll";
  uuid = "35661453-b289-5fab-8a00-3d9160c6a3a4";
  path = "X/Xorg_xkbcomp_jll";
  replaceUrlInManifest = null;
  treehash = "4bcbf660f6c2e714f87e960a171b119d06ee163b";
  artifacts = {
    "2022ba6725de1af78cae27ce0d5e8c105e9ed192" = [{
      name = "Xorg_xkbcomp";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+3/Xorg_xkbcomp.v1.4.2.x86_64-linux-gnu.tar.gz";
      sha256 = "fadda48d06b79e4dfd6f5803e09f42e924e6fef9ceeb250cb4963e300d19969a";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl.git"; rev = "4bcbf660f6c2e714f87e960a171b119d06ee163b"; sha256 = "18jf1n1ia6x83ig3m8plipr4wvp8hmlgzlw41ap6lcgvvp273jmv"; };
} {
  name = "Xorg_xkeyboard_config_jll";
  uuid = "33bec58e-1273-512f-9401-5d533626f822";
  path = "X/Xorg_xkeyboard_config_jll";
  replaceUrlInManifest = null;
  treehash = "5c8424f8a67c3f2209646d4425f3d415fee5931d";
  artifacts = {
    "be58fe5ecba3c97f24d6d6d13540b73f19c73e6f" = [{
      name = "Xorg_xkeyboard_config";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl/releases/download/Xorg_xkeyboard_config-v2.27.0+3/Xorg_xkeyboard_config.v2.27.0.x86_64-linux-gnu.tar.gz";
      sha256 = "39640762597118365679c1c5a509804cefce0c4d79fa7c0af4f1f2b5e8d0d50a";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xkeyboard_config_jll.jl.git"; rev = "5c8424f8a67c3f2209646d4425f3d415fee5931d"; sha256 = "00vci80hshh9fn9plwclnjl327fn8p3q13v83rhvnazr8lwbrabr"; };
} {
  name = "Xorg_xtrans_jll";
  uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10";
  path = "X/Xorg_xtrans_jll";
  replaceUrlInManifest = null;
  treehash = "79c31e7844f6ecf779705fbc12146eb190b7d845";
  artifacts = {
    "45f6b81caf89f7e08b1253217d7deb82d0af6822" = [{
      name = "Xorg_xtrans";
      url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl/releases/download/Xorg_xtrans-v1.4.0+2/Xorg_xtrans.v1.4.0.x86_64-linux-gnu.tar.gz";
      sha256 = "14a4b2c4afb360c15c49beabe614555af305a5d1d5328f2fb37de22d682ad70e";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Xorg_xtrans_jll.jl.git"; rev = "79c31e7844f6ecf779705fbc12146eb190b7d845"; sha256 = "0vsy8jqfzfiw9hin947674a99z2b8b7vjcy96x5z1w0qsy8ba7w8"; };
} {
  name = "ZMQ";
  uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1";
  path = "Z/ZMQ";
  replaceUrlInManifest = null;
  treehash = "356d2bdcc0bce90aabee1d1c0f6d6f301eda8f77";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaInterop/ZMQ.jl.git"; rev = "356d2bdcc0bce90aabee1d1c0f6d6f301eda8f77"; sha256 = "10qfvnm605xy3c70gnwxdd9s56sq6j40cm7g9yx1zw89lbkpx67a"; };
} {
  name = "ZeroMQ_jll";
  uuid = "8f1865be-045e-5c20-9c9f-bfbfb0764568";
  path = "Z/ZeroMQ_jll";
  replaceUrlInManifest = null;
  treehash = "fe5c65a526f066fb3000da137d5785d9649a8a47";
  artifacts = {
    "a34d055904c066b77226ece4b85011819de73136" = [{
      name = "ZeroMQ";
      url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.4+0/ZeroMQ.v4.3.4.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "6a3400f7a23a3f99c40c0ab1c50b5a545007a229bb7b2ea6cf6eaf8b87a94b53";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl.git"; rev = "fe5c65a526f066fb3000da137d5785d9649a8a47"; sha256 = "05f42mnpm1dyzzfazzpvy6rwlxbgqyhx6zfycvs40r435sqzlsbf"; };
} {
  name = "Zlib_jll";
  uuid = "83775a58-1f1d-513f-b197-d71354ab007a";
  path = "Z/Zlib_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Zstd_jll";
  uuid = "3161d3a3-bdf6-5164-811a-617609db77b4";
  path = "Z/Zstd_jll";
  replaceUrlInManifest = null;
  treehash = "e45044cd873ded54b6a5bac0eb5c971392cf1927";
  artifacts = {
    "d22cde7583df1d5f71160a8e4676955a66a91f33" = [{
      name = "Zstd";
      url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl/releases/download/Zstd-v1.5.2+0/Zstd.v1.5.2.x86_64-linux-gnu.tar.gz";
      sha256 = "9d0fff908e3e0273cc8360a3fb4696e4227bc5cd0dd10bd3a4c9d295b9e4e25e";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Zstd_jll.jl.git"; rev = "e45044cd873ded54b6a5bac0eb5c971392cf1927"; sha256 = "0ln93967146qhm2hxw12wcqk26npbrf1w0pjrazmh0gnd7gpwwlf"; };
} {
  name = "fzf_jll";
  uuid = "214eeab7-80f7-51ab-84ad-2988db7cef09";
  path = "F/fzf_jll";
  replaceUrlInManifest = null;
  treehash = "868e669ccb12ba16eaf50cb2957ee2ff61261c56";
  artifacts = {
    "6248cb1f54b1805fa1eaeeefc0f2d75f4435e69d" = [{
      name = "fzf";
      url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.29.0+0/fzf.v0.29.0.x86_64-linux-gnu.tar.gz";
      sha256 = "d6be08bcdab0bd2724693350698e96a307f22aa728fed1a6805d4364e280ba4e";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl.git"; rev = "868e669ccb12ba16eaf50cb2957ee2ff61261c56"; sha256 = "0fql7ak0nhry8wxh6jrhvnbz94ls8lzh6wx22pm9nyrzqk8cr8rg"; };
} {
  name = "libaom_jll";
  uuid = "a4ae2306-e953-59d6-aa16-d00cac43593b";
  path = "L/libaom_jll";
  replaceUrlInManifest = null;
  treehash = "3a2ea60308f0996d26f1e5354e10c24e9ef905d4";
  artifacts = {
    "595f9476b128877ab5bf73883ff6c8dc8dacfe66" = [{
      name = "libaom";
      url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.4.0+0/libaom.v3.4.0.x86_64-linux-gnu-cxx11.tar.gz";
      sha256 = "a3a9df2a3fdce42edb3d1f0692ca68f2da301b3c963641e6dd3de7f215f2b96a";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl.git"; rev = "3a2ea60308f0996d26f1e5354e10c24e9ef905d4"; sha256 = "03i0n2a0mn2yi4m0ci2ppsvafdh9fx8yn63kh6yk8h9p5m2crn6n"; };
} {
  name = "libass_jll";
  uuid = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0";
  path = "L/libass_jll";
  replaceUrlInManifest = null;
  treehash = "5982a94fcba20f02f42ace44b9894ee2b140fe47";
  artifacts = {
    "459252c01ffcd08700841efdd4b6d3edfe5916e7" = [{
      name = "libass";
      url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.15.1+0/libass.v0.15.1.x86_64-linux-gnu.tar.gz";
      sha256 = "c7e44a4873ee15ce74a0c01452f8e9d0891cddd07a839630c337a4183a889bb5";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl.git"; rev = "5982a94fcba20f02f42ace44b9894ee2b140fe47"; sha256 = "0ffl8gk9v7cf9ha4v2vjg56fgbgikbsgipibycc5464c7v3dni8d"; };
} {
  name = "libblastrampoline_jll";
  uuid = "8e850b90-86db-534c-a0d3-1478176c7d93";
  path = "L/libblastrampoline_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "libfdk_aac_jll";
  uuid = "f638f0a6-7fb0-5443-88ba-1cc74229b280";
  path = "L/libfdk_aac_jll";
  replaceUrlInManifest = null;
  treehash = "daacc84a041563f965be61859a36e17c4e4fcd55";
  artifacts = {
    "cc415631aeb190b075329ce756f690a90e1f873b" = [{
      name = "libfdk_aac";
      url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v2.0.2+0/libfdk_aac.v2.0.2.x86_64-linux-gnu.tar.gz";
      sha256 = "7180dacdb5abb7103331f9fec4b0fe0d1a67857075a3680898ac9f8e75895617";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl.git"; rev = "daacc84a041563f965be61859a36e17c4e4fcd55"; sha256 = "1cgd5l75m7srzgfwih5bblsqdphi1d04v10yq5ny3nswi5lrfs5y"; };
} {
  name = "libpng_jll";
  uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f";
  path = "L/libpng_jll";
  replaceUrlInManifest = null;
  treehash = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c";
  artifacts = {
    "ddfc455343aff48d27c1b39d7fcb07e0d9242b50" = [{
      name = "libpng";
      url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.38+0/libpng.v1.6.38.x86_64-linux-gnu.tar.gz";
      sha256 = "444268a49548a199d471769bd2d6438fd43b61597c2511249d34b300d19ecff2";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl.git"; rev = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c"; sha256 = "09r4wv477lc9fjg86nikni06r0rjl9bwnrr2rdbfsxjd8g08lfzz"; };
} {
  name = "libsodium_jll";
  uuid = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8";
  path = "L/libsodium_jll";
  replaceUrlInManifest = null;
  treehash = "848ab3d00fe39d6fbc2a8641048f8f272af1c51e";
  artifacts = {
    "1fce04a1a7eedfdf2b0b81ca9001494525764e11" = [{
      name = "libsodium";
      url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl/releases/download/libsodium-v1.0.20+0/libsodium.v1.0.20.x86_64-linux-gnu.tar.gz";
      sha256 = "873dafbb0cf4eee9fa603c4f8ee7863c6d514da1ba312d1aed4a1f0f45299919";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl.git"; rev = "848ab3d00fe39d6fbc2a8641048f8f272af1c51e"; sha256 = "15bxg4kd0pwp809c8yxw8hgnhfrh328crpfa5xd7rnbwfd2rg8qr"; };
} {
  name = "libvorbis_jll";
  uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a";
  path = "L/libvorbis_jll";
  replaceUrlInManifest = null;
  treehash = "b910cb81ef3fe6e78bf6acee440bda86fd6ae00c";
  artifacts = {
    "89ed5dda220da4354ada1970107e13679914bbbc" = [{
      name = "libvorbis";
      url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.7+1/libvorbis.v1.3.7.x86_64-linux-gnu.tar.gz";
      sha256 = "d314fdcb60bfeefdcdfd949f39ded6c75721f56f46aa83d66af019083e695066";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl.git"; rev = "b910cb81ef3fe6e78bf6acee440bda86fd6ae00c"; sha256 = "1yqvyav7pradfn81mrr6jb40436kcqhyvqqvf6xjsi4nhfpj8ldy"; };
} {
  name = "nghttp2_jll";
  uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d";
  path = "N/nghttp2_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "p7zip_jll";
  uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0";
  path = "P/p7zip_jll";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "x264_jll";
  uuid = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a";
  path = "X/x264_jll";
  replaceUrlInManifest = null;
  treehash = "4fea590b89e6ec504593146bf8b988b2c00922b2";
  artifacts = {
    "587de110e5f58fd435dc35b294df31bb7a75f692" = [{
      name = "x264";
      url = "https://github.com/JuliaBinaryWrappers/x264_jll.jl/releases/download/x264-v2021.5.5+0/x264.v2021.5.5.x86_64-linux-gnu.tar.gz";
      sha256 = "d2c6713284a23538db197b579a7669dff3688cf6f72cb1f81019a46cc24198a2";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/x264_jll.jl.git"; rev = "4fea590b89e6ec504593146bf8b988b2c00922b2"; sha256 = "06iiv2r74k6a9dyi0fbwni175dipg9ac05xzvbyc9msvsph76w6a"; };
} {
  name = "x265_jll";
  uuid = "dfaa095f-4041-5dcd-9319-2fabd8486b76";
  path = "X/x265_jll";
  replaceUrlInManifest = null;
  treehash = "ee567a171cce03570d77ad3a43e90218e38937a9";
  artifacts = {
    "fc239b3ff5739aeab252bd154fa4dd045fefe629" = [{
      name = "x265";
      url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v3.5.0+0/x265.v3.5.0.x86_64-linux-gnu.tar.gz";
      sha256 = "c13c7606c7fc319913e3bf516c6c49af23a2dd37e8acdacf33978828d2c0de03";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl.git"; rev = "ee567a171cce03570d77ad3a43e90218e38937a9"; sha256 = "1vkrjlpwqdqx1bcqm948j22abdrgms847sp1bj59fzp7vg7sgrdi"; };
} {
  name = "xkbcommon_jll";
  uuid = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd";
  path = "X/xkbcommon_jll";
  replaceUrlInManifest = null;
  treehash = "9ebfc140cc56e8c2156a15ceac2f0302e327ac0a";
  artifacts = {
    "4443e44120d70a97f8094a67268a886256077e69" = [{
      name = "xkbcommon";
      url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl/releases/download/xkbcommon-v1.4.1+0/xkbcommon.v1.4.1.x86_64-linux-gnu.tar.gz";
      sha256 = "580953526c4e6537e387a75199bc69a397cabe43b69183de791100e2e8d9e95d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/xkbcommon_jll.jl.git"; rev = "9ebfc140cc56e8c2156a15ceac2f0302e327ac0a"; sha256 = "00fjfpwv83kqqnz0g2cd71s561kgvc4jhyfj69izprml1hiwlqag"; };
}];
}
