#! /usr/bin/env bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTDIR/.."

set -e

OUTPUT=$(nix build .#optionsCommonMark --no-link --json | jq -r '.[0].outputs.out')

cp "$OUTPUT" ./OPTIONS.md
chmod u+x ./OPTIONS.md
